ACQ200 HOSTDRV: acq200_i2o.c File Reference
acq200_i2o.c File Reference
i2o message passing implementation.
#include <linux/kernel.h>
#include <linux/pci.h>
#include <linux/time.h>
#include <linux/init.h>
#include <linux/interrupt.h>
#include <linux/timex.h>
#include <linux/vmalloc.h>
#include <linux/mm.h>
#include <linux/proc_fs.h>
#include <asm/uaccess.h>
#include "acq32busprot.h"
#include "acq200.h"
#include "acq200_debug.h"
#include "acq200_ioctl.h"
#include "rch.h"
Defines
#define I2O_RETRY(device) (1 + HZ/10 + (device)->idx)
#define DUMPHRD(var) dumpHrd(#var, var)
#define CHAN(file) ((file)->f_dentry->d_inode->i_rdev&0x00ff)
#define MFA_MASK 0x00ffffff
Functions
static void dumpHrd (const char *name, struct HOST_REQUEST_DATA_RECORD *hrd)
static Message * build_hrd_message (struct file *file, unsigned pa, unsigned start, unsigned length, unsigned stride, int outbound, unsigned short cflags)
static Message * build_outgoing_raw_message (struct file *file, unsigned pa, unsigned start_byte, unsigned nbytes, unsigned short cflags)
static Message * build_incoming_raw_message (struct file *file, unsigned pa, unsigned start_byte, unsigned nbytes, unsigned short cflags)
static void buildRch (struct ReturnCommandHandler *rch, void(*handler)(struct ReturnCommandHandler *this, struct MESSAGE *messsage), struct Acq200Path *path, struct IoMapping *kbuf, unsigned flags)
int acq200_sendI2O_kbuf (struct Acq200Path *path, Message *message)
int acq200_copy_from_io_to_user (struct file *file, void *ubuf, const void *iobuf, int count)
int acq200_copy_from_user_to_io (struct file *file, void *iobuf, const void *ubuf, int count)
static void i2o_recycleRch (struct ReturnCommandHandler *self)
static void i2o_recycleRchWrapper (struct ReturnCommandHandler *self, struct MESSAGE *unused)
static void i2o_handleReadMessageFile (struct ReturnCommandHandler *self, struct MESSAGE *response)
static void acq200_dev_i2o_return_mfa (struct Acq200Device *device, unsigned mfa)
static void * acq200_dev_i2o_mfa2va (struct Acq200Device *device, u32 mfa)
static int i2o_return_message (struct Acq200Device *device, unsigned mfa)
static void acq200_processCommandMessageReturn (struct Acq200Device *device, Message *message)
void acq200_streaming_isr_bh (unsigned long clidata)
void acq200_consume_i2o (struct Acq200Device *device, u32 mfa)
static void i2o_handleLastMessage (struct ReturnCommandHandler *self, struct MESSAGE *response)
ssize_t acq200_bridge_read_generic (struct file *file, char *buf, size_t count, loff_t *posp, int hrd_code, struct IoMapping *kbuf)
ssize_t acq200_bridge_write_generic (struct file *file, const char *buf, size_t count, loff_t *posp, int hrd_code)
ssize_t acq200_bridge_write (struct file *file, const char *buf, size_t count, loff_t *posp)
ssize_t acq200_bridge_read (struct file *file, char *buf, size_t count, loff_t *posp)
ssize_t acq200_bridge_readAB (struct file *file, char *buf, size_t count, loff_t *posp)
void _recycle (struct Acq200Path *path, int ibuf)
void acq200_bufferABrecycle (struct file *file, struct BufferAB_Ops *ops)
static int fillDeviceStatus (struct BufferAB_Ops *ops, struct Acq200Path *path)
static void acq200_bufferAB_queue (struct file *file, int buffer)
int i2o_missed_int_checker (void *arg)
int acq200_bufferABaction (struct file *file, struct BufferAB_Ops *ops)
static void _cleanup_on_bridge_release (struct Acq200Path *path)
static int acq200_bridge_release_message (struct inode *inode, struct file *file, Message *message)
int acq200_bridge_release_generic (struct inode *inode, struct file *file, int hrd_code)
int acq200_bridge_release (struct inode *inode, struct file *file)
void rchInit (struct Acq200Device *device, struct ReturnCommandHandler *rch)
Variables
int user_max_buf
Detailed Description
i2o message passing implementation.
Definition in file acq200_i2o.c.
Define Documentation
#define CHAN (file) ((file)->f_dentry->d_inode->i_rdev&0x00ff)
Definition at line 71 of file acq200_i2o.c.
Referenced by build_hrd_message().
#define DUMPHRD (var) dumpHrd(#var, var)
Definition at line 69 of file acq200_i2o.c.
Referenced by i2o_handleReadMessageFile().
#define I2O_RETRY (device) (1 + HZ/10 + (device)->idx)
Definition at line 58 of file acq200_i2o.c.
Referenced by i2o_missed_int_checker().
#define MFA_MASK 0x00ffffff
Definition at line 162 of file acq200_i2o.c.
Referenced by acq200_sendI2O_kbuf().
Function Documentation
static void _cleanup_on_bridge_release (struct Acq200Path * path) [static]
Definition at line 786 of file acq200_i2o.c.
References ReturnCommandHandler::command_id, dbg, Acq200Path::device, i2o_recycleRch(), RchReturn::kbuf, ReturnCommandHandler::list, Acq200Device::DevicePrivateData::rch::list, Acq200Device::m_dpd, ReturnCommandHandler::path, Acq200Device::DevicePrivateData::rch, and ReturnCommandHandler::rchReturn.
Referenced by acq200_bridge_release_generic(), and acq200_bridge_release_message().
void _recycle (struct Acq200Path * path, int ibuf)
Definition at line 630 of file acq200_i2o.c.
References dbg, i2o_recycleRch(), and Acq200Path::rchAB.
Referenced by acq200_bufferABrecycle().
ssize_t acq200_bridge_read (struct file * file, char * buf, size_t count, loff_t * posp)
Definition at line 604 of file acq200_i2o.c.
References acq200_bridge_read_generic(), HRD_CHAN_IS_FILE, and USE_POOL.
Referenced by acq200_open().
ssize_t acq200_bridge_read_generic (struct file * file, char * buf, size_t count, loff_t * posp, int hrd_code, struct IoMapping * kbuf)
Definition at line 458 of file acq200_i2o.c.
References acq200_copy_from_io_to_user(), acq200_pool_alloc_mapping(), acq200_pool_alloc_rch(), acq200_pool_free_mapping(), acq200_sendI2O_kbuf(), build_incoming_raw_message(), buildRch(), dbg, DEV, i2o_handleReadMessageFile(), i2o_recycleRch(), RchReturn::kbuf, Acq200Device::DevicePrivateData::rch::list, Acq200Device::m_dpd, MK_DMABUF_OFFSET, RchReturn::nbytes, Acq200Device::pci_dev, PD, Acq200Device::DevicePrivateData::rch, RCH_KB_POOL, rchAppend(), rchRemoveIfNotValid(), ReturnCommandHandler::rchReturn, and RchReturn::valid.
Referenced by acq200_bridge_read(), and acq200_bridge_readAB().
ssize_t acq200_bridge_readAB (struct file * file, char * buf, size_t count, loff_t * posp)
Definition at line 611 of file acq200_i2o.c.
References Acq200Device::AB, acq200_bridge_read_generic(), dbg, DEV, dma_buf_len(), HRD_ABS_PCI, HRD_CHAN_IS_FILE, DmaBuf::pa, user_max_buf, and DmaBuf::va.
Referenced by acq200_open().
int acq200_bridge_release (struct inode * inode, struct file * file)
Definition at line 865 of file acq200_i2o.c.
References acq200_bridge_release_generic(), and HRD_CHAN_IS_FILE.
Referenced by acq200_bridge_releaseAB(), and acq200_open().
int acq200_bridge_release_generic (struct inode * inode, struct file * file, int hrd_code)
Definition at line 840 of file acq200_i2o.c.
References _cleanup_on_bridge_release(), acq200_bridge_release_message(), acq200_release(), build_incoming_raw_message(), build_outgoing_raw_message(), dbg, HRD_CHAN_EOF, Acq200Path::last_direction_hack, LDH_INBOUND, LDH_OUTBOUND, and PD.
Referenced by acq200_bridge_release().
static int acq200_bridge_release_message (struct inode * inode, struct file * file, Message * message) [static]
Definition at line 806 of file acq200_i2o.c.
References _cleanup_on_bridge_release(), acq200_pool_alloc_rch(), acq200_release(), acq200_sendI2O_kbuf(), buildRch(), dbg, Acq200Path::device, err, i2o_handleLastMessage(), i2o_recycleRch(), Acq200Device::DevicePrivateData::rch::list, Acq200Device::m_dpd, PD, Acq200Device::DevicePrivateData::rch, RCH_KB_POOL, rchAppend(), ReturnCommandHandler::rchReturn, Acq200Path::return_waitq, and RchReturn::valid.
Referenced by acq200_bridge_release_generic().
ssize_t acq200_bridge_write (struct file * file, const char * buf, size_t count, loff_t * posp)
Definition at line 594 of file acq200_i2o.c.
References acq200_bridge_write_generic(), dbg, and HRD_CHAN_IS_FILE.
Referenced by acq200_open().
ssize_t acq200_bridge_write_generic (struct file * file, const char * buf, size_t count, loff_t * posp, int hrd_code)
Definition at line 542 of file acq200_i2o.c.
References acq200_copy_from_user_to_io(), acq200_pool_alloc_mapping(), acq200_pool_alloc_rch(), acq200_sendI2O_kbuf(), build_outgoing_raw_message(), buildRch(), dbg, DEV, Acq200Device::dma_buf, MESSAGE::hrdr, i2o_recycleRch(), i2o_recycleRchWrapper(), RchReturn::kbuf, Acq200Device::DevicePrivateData::rch::list, Acq200Device::m_dpd, MK_DMABUF_OFFSET, DmaBuf::pa, MESSAGE::payload, HOST_REQUEST_DATA_RECORD::pci, Acq200Device::pci_dev, PD, Acq200Device::DevicePrivateData::rch, RCH_KB_POOL, rchAppend(), and ReturnCommandHandler::rchReturn.
Referenced by acq200_bridge_write().
static void acq200_bufferAB_queue (struct file * file, int buffer) [static]
Definition at line 678 of file acq200_i2o.c.
References Acq200Device::AB, acq200_pool_alloc_rch(), acq200_sendI2O_kbuf(), Acq200Path::bufferMappings, build_hrd_message(), buildRch(), dbg, DEV, dma_buf_len(), HRD_ABS_PCI, HRD_CHAN_IS_FILE, HRD_READ_NEXT, i2o_handleReadMessageFile(), LDH_INBOUND, Acq200Device::DevicePrivateData::rch::list, Acq200Device::m_dpd, DmaBuf::pa, PD, Acq200Device::DevicePrivateData::rch, RCH_KB_POOL, Acq200Path::rchAB, rchAppend(), Acq200Path::sid, user_max_buf, and DmaBuf::va.
Referenced by acq200_bufferABaction().
int acq200_bufferABaction (struct file * file, struct BufferAB_Ops * ops)
Definition at line 739 of file acq200_i2o.c.
References Acq200Path::ab_next, acq200_bufferAB_queue(), acq200_bufferABrecycle(), BUFFERA, BUFFERB, BufferAB_Ops::ci, dbg, BufferAB_Ops::ds, err, fillDeviceStatus(), BufferAB_Ops::DriverStatus::full, PD, Acq200Path::rchAB, ReturnCommandHandler::rchReturn, Acq200Path::return_waitq, BufferAB_Ops::ClientInstructions::timeout, and RchReturn::valid.
Referenced by acq200_ioctlAB().
void acq200_bufferABrecycle (struct file * file, struct BufferAB_Ops * ops)
Definition at line 640 of file acq200_i2o.c.
References _recycle(), BUFFER_A_FLAG, BUFFER_B_FLAG, BUFFERA, BUFFERB, BufferAB_Ops::ci, PD, and BufferAB_Ops::ClientInstructions::recycle.
Referenced by acq200_bufferABaction().
void acq200_consume_i2o (struct Acq200Device * device, u32 mfa)
Definition at line 413 of file acq200_i2o.c.
References acq200_debug, dbg, Acq200Device::DevicePrivateData::i2o_last_in, Acq200Device::DevicePrivateData::i2o_packets_discarded, Acq200Device::DevicePrivateData::i2o_packets_incoming, i2o_return_message(), Acq200Device::m_dpd, Acq200Device::streambuf, Acq200Device::DevicePrivateData::streaming_isr_tasklet, streamPut(), and TIMESTAMP.
Referenced by acq200_handle_incoming_message(), and acq200_incoming_message_isr().
int acq200_copy_from_io_to_user (struct file * file, void * ubuf, const void * iobuf, int count)
Definition at line 213 of file acq200_i2o.c.
References acq200_stub_copy_to_user, and dbg.
Referenced by acq200_bridge_read_generic().
int acq200_copy_from_user_to_io (struct file * file, void * iobuf, const void * ubuf, int count)
Definition at line 224 of file acq200_i2o.c.
References dbg.
Referenced by acq200_bridge_write_generic().
static void* acq200_dev_i2o_mfa2va (struct Acq200Device * device, u32 mfa) [static]
Definition at line 286 of file acq200_i2o.c.
References ACQ200_PCIWINMSK, Acq200Device::dma_buf, and DmaBuf::va.
Referenced by acq200_streaming_isr_bh().
static void acq200_dev_i2o_return_mfa (struct Acq200Device * device, unsigned mfa) [static]
Definition at line 279 of file acq200_i2o.c.
References ACQ200_OQP, CSR, and dbg.
Referenced by i2o_return_message().
static void acq200_processCommandMessageReturn (struct Acq200Device * device, Message * message) [static]
Definition at line 305 of file acq200_i2o.c.
References ReturnCommandHandler::command_id, dbg, ReturnCommandHandler::handler, MESSAGE::header, Acq200Device::DevicePrivateData::i2o_packets_discarded, i2o_recycleRch(), MESSAGE_HEADER::id, RchReturn::kbuf, ReturnCommandHandler::list, Acq200Device::DevicePrivateData::rch::list, Acq200Device::m_dpd, Acq200Device::DevicePrivateData::rch, and ReturnCommandHandler::rchReturn.
Referenced by acq200_streaming_isr_bh().
int acq200_sendI2O_kbuf (struct Acq200Path * path, Message * message)
Definition at line 164 of file acq200_i2o.c.
References ACQ200_IQP, CSR, dbg, Acq200Path::device, EACQ32_NO_INCOMING_I2O, MESSAGE::header, Acq200Device::DevicePrivateData::i2o_last_id_out, Acq200Device::DevicePrivateData::i2o_packets_outgoing, MESSAGE_HEADER::id, MESSAGE_HEADER::length, Acq200Device::m_dpd, MAKE_ID_DTACQ, MESSAGE_ACTUAL_LEN, MFA_MASK, Acq200Device::IoMapping::pa, MESSAGE::payload, Acq200Device::pci_dev, PCI_I2O_INVALID_MFA, Acq200Device::ram, MESSAGE::sdata, MESSAGE_HEADER::type, and Acq200Device::IoMapping::va.
Referenced by acq200_bridge_read_generic(), acq200_bridge_release_message(), acq200_bridge_write_generic(), and acq200_bufferAB_queue().
void acq200_streaming_isr_bh (unsigned long clidata)
Definition at line 348 of file acq200_i2o.c.
References acq200_debug, acq200_dev_i2o_mfa2va(), acq200_processCommandMessageReturn(), Acq200Device::DevicePrivateData::aux_mfa, Acq200Device::DevicePrivateData::aux_task_waiting, Acq200Device::DevicePrivateData::aux_waitq, dbg, MESSAGE::header, Acq200Device::DevicePrivateData::i2o_packets_discarded, i2o_return_message(), MESSAGE_HEADER::id, MESSAGE_HEADER::length, Acq200Device::m_dpd, MT_COMMAND_PACKET, MT_ID, MT_STREAM, STREAM_MFA_INVALID, Acq200Device::streambuf, streamGet(), Acq200Device::DevicePrivateData::streaming_enabled, streamPut(), TIMESTAMP, and MESSAGE_HEADER::type.
Referenced by acq200_device_create().
static Message* build_hrd_message (struct file * file, unsigned pa, unsigned start, unsigned length, unsigned stride, int outbound, unsigned short cflags) [static]
Definition at line 73 of file acq200_i2o.c.
References CHAN, HOST_REQUEST_DATA_RECORD::chan, dbg, MESSAGE::header, MESSAGE::hrdr, HRDR_SZ, LBUF, MESSAGE_HEADER::length, MAKE_MT_COMMAND, MTC_HOST_REQUEST_DATA_ACQBOUND, MTC_HOST_REQUEST_DATA_HOSTBOUND, HOST_REQUEST_DATA_RECORD::nsamples, MESSAGE::payload, HOST_REQUEST_DATA_RECORD::pci, PD, HOST_REQUEST_DATA_RECORD::start, HOST_REQUEST_DATA_RECORD::stride, and MESSAGE_HEADER::type.
Referenced by acq200_bufferAB_queue(), build_incoming_raw_message(), and build_outgoing_raw_message().
static Message* build_incoming_raw_message (struct file * file, unsigned pa, unsigned start_byte, unsigned nbytes, unsigned short cflags) [static]
Definition at line 129 of file acq200_i2o.c.
References build_hrd_message(), and LDH_INBOUND.
Referenced by acq200_bridge_read_generic(), and acq200_bridge_release_generic().
static Message* build_outgoing_raw_message (struct file * file, unsigned pa, unsigned start_byte, unsigned nbytes, unsigned short cflags) [static]
Definition at line 117 of file acq200_i2o.c.
References build_hrd_message(), and LDH_OUTBOUND.
Referenced by acq200_bridge_release_generic(), and acq200_bridge_write_generic().
static void buildRch (struct ReturnCommandHandler * rch, void(*)(struct ReturnCommandHandler *this, struct MESSAGE *messsage) handler, struct Acq200Path * path, struct IoMapping * kbuf, unsigned flags) [static]
Definition at line 142 of file acq200_i2o.c.
References ReturnCommandHandler::command_id, Acq200Path::device, ReturnCommandHandler::device, RchReturn::flags, ReturnCommandHandler::handler, Acq200Device::DevicePrivateData::i2o_last_id_out, RchReturn::kbuf, Acq200Device::DevicePrivateData::rch::lock, ReturnCommandHandler::lock, Acq200Device::m_dpd, MAKE_ID_DTACQ, RchReturn::nbytes, ReturnCommandHandler::path, Acq200Device::DevicePrivateData::rch, ReturnCommandHandler::rchReturn, and RchReturn::valid.
Referenced by acq200_bridge_read_generic(), acq200_bridge_release_message(), acq200_bridge_write_generic(), and acq200_bufferAB_queue().
static void dumpHrd (const char * name, struct HOST_REQUEST_DATA_RECORD * hrd) [static]
Definition at line 61 of file acq200_i2o.c.
References HOST_REQUEST_DATA_RECORD::chan, dbg, HOST_REQUEST_DATA_RECORD::nsamples, HOST_REQUEST_DATA_RECORD::pci, HOST_REQUEST_DATA_RECORD::start, and HOST_REQUEST_DATA_RECORD::stride.
static int fillDeviceStatus (struct BufferAB_Ops * ops, struct Acq200Path * path) [static]
Definition at line 652 of file acq200_i2o.c.
References Acq200Path::ab_next, BUFFER_FLAG_LUT, BUFFERA, BUFFERB, dbg, Acq200Path::device, BufferAB_Ops::ds, BufferAB_Ops::DriverStatus::full, FULL_EOF, RchReturn::kbuf, BufferAB_Ops::DriverStatus::len, RchReturn::nbytes, Acq200Device::pci_dev, Acq200Path::rchAB, ReturnCommandHandler::rchReturn, BufferAB_Ops::DriverStatus::sid, RchReturn::start_id, and RchReturn::valid.
Referenced by acq200_bufferABaction().
static void i2o_handleLastMessage (struct ReturnCommandHandler * self, struct MESSAGE * response) [static]
Definition at line 447 of file acq200_i2o.c.
References i2o_recycleRch().
Referenced by acq200_bridge_release_message().
static void i2o_handleReadMessageFile (struct ReturnCommandHandler * self, struct MESSAGE * response) [static]
Definition at line 256 of file acq200_i2o.c.
References dbg, DUMPHRD, MESSAGE::hrdr, i2o_recycleRch(), HOST_REQUEST_DATA_RECORD::nsamples, MESSAGE::payload, rchSetSamplesAndGetPath(), Acq200Path::return_waitq, and HOST_REQUEST_DATA_RECORD::start.
Referenced by acq200_bridge_read_generic(), and acq200_bufferAB_queue().
int i2o_missed_int_checker (void * arg)
Definition at line 709 of file acq200_i2o.c.
References acq200_handle_incoming_message(), dbg, I2O_RETRY, Acq200Device::idx, info, and timeout.
Referenced by acq200_onFirstClientOpenAB().
static void i2o_recycleRch (struct ReturnCommandHandler * self) [static]
Definition at line 232 of file acq200_i2o.c.
References acq200_pool_free_mapping(), acq200_pool_free_rch(), dbg, RCH_KB_POOL, and rchRemove().
Referenced by _cleanup_on_bridge_release(), _recycle(), acq200_bridge_read_generic(), acq200_bridge_release_message(), acq200_bridge_write_generic(), acq200_processCommandMessageReturn(), i2o_handleLastMessage(), i2o_handleReadMessageFile(), and i2o_recycleRchWrapper().
static void i2o_recycleRchWrapper (struct ReturnCommandHandler * self, struct MESSAGE * unused) [static]
Definition at line 248 of file acq200_i2o.c.
References i2o_recycleRch().
Referenced by acq200_bridge_write_generic().
static int i2o_return_message (struct Acq200Device * device, unsigned mfa) [static]
Definition at line 293 of file acq200_i2o.c.
References acq200_dev_i2o_return_mfa(), Acq200Device::DevicePrivateData::i2o_packets_returned, and Acq200Device::m_dpd.
Referenced by acq200_consume_i2o(), and acq200_streaming_isr_bh().
void rchInit (struct Acq200Device * device, struct ReturnCommandHandler * rch)
Definition at line 874 of file acq200_i2o.c.
References ReturnCommandHandler::handler, ReturnCommandHandler::list, Acq200Device::DevicePrivateData::rch::list, ReturnCommandHandler::lock, Acq200Device::DevicePrivateData::rch::lock, Acq200Device::m_dpd, and Acq200Device::DevicePrivateData::rch.
Referenced by _create_handlers(), and acq200_device_create().
Variable Documentation
int user_max_buf
Definition at line 298 of file acq200.c.
Referenced by acq200_bridge_readAB(), and acq200_bufferAB_queue().