ACQ200 HOSTDRV: acq200_core.c File Reference
acq200_core.c File Reference
core functionality
#include <linux/kernel.h>
#include <linux/pci.h>
#include <linux/time.h>
#include <linux/interrupt.h>
#include <linux/init.h>
#include <linux/timex.h>
#include <linux/vmalloc.h>
#include <linux/mm.h>
#include <linux/moduleparam.h>
#include <linux/proc_fs.h>
#include <asm/pgtable.h>
#include <asm/uaccess.h>
#include "acq200_debug.h"
#include "acq200.h"
#include "acq200_minors.h"
#include "acq32busprot.h"
Functions
static unsigned _getHeartbeat (struct Acq200Device *device)
int acq200_getHeartbeat (struct Acq200Device *device)
int acq200_getAvailableChannels (struct Acq200Device *device)
send a query, pick up answers for aX != NULL
Detailed Description
core functionality
Definition in file acq200_core.c.
Function Documentation
static unsigned _getHeartbeat (struct Acq200Device * device) [static]
Definition at line 51 of file acq200_core.c.
References BP_GET_HEARTBEAT, BP_MB_STATUS, and MBOX_READ.
Referenced by acq200_getHeartbeat().
int acq200_getAvailableChannels (struct Acq200Device * device)
send a query, pick up answers for aX != NULL
update available input, output channels from device
Definition at line 102 of file acq200_core.c.
References acq200_sendQuery(), BP_SET_FUNCODE, BPFC_GET_NCHANNELS, err, Acq200Device::input_channels, Acq200Device::CHANNEL_INFO::nchannels, NULL_A3, NULL_A4, and Acq200Device::output_channels.
Referenced by acq200_device_init().
int acq200_getHeartbeat (struct Acq200Device * device)
Definition at line 56 of file acq200_core.c.
References _getHeartbeat(), dbg, Acq200Device::heartbeat_detected, and MBOX_READ.
Referenced by show_heartbeat().