ACQ200 HOSTDRV: acq200.c File Reference
acq200.c File Reference
core Linux 2.6.x host pci driver for D-TACQ ACQ2xx cards.
#include <linux/device.h>
#include <linux/interrupt.h>
#include <linux/kernel.h>
#include <linux/pci.h>
#include <linux/time.h>
#include <linux/init.h>
#include <linux/timex.h>
#include <linux/vmalloc.h>
#include <linux/mm.h>
#include <linux/moduleparam.h>
#include <linux/proc_fs.h>
#include <asm/uaccess.h>
#include <linux/module.h>
#include "acq32busprot.h"
#include "acq200_debug.h"
#include "acq200.h"
#include "acq200_minors.h"
#include "acq200_ioctl.h"
#include "acq32ioctl.h"
#include "rch.h"
Defines
#define EXPORT_SYMTAB
#define MAXDEV 16
#define DEFTO HZ
parameters - useful, but beware these are global
#define LINUX26_MAXALLOC_PAGE_ORDER 12
#define COMMSBUF_ORDER LINUX26_MAXALLOC_PAGE_ORDER
communications buffer must have a large minimum size.
#define BIGTIME 0x7fffffff
#define MBX_READ 1
#define IRQ_IGNORE (ACQ200_OISR_OM_0|ACQ200_OISR_OM_1)
#define MYTURN 1
#define RETURN_OPEN_NEWFOPS(newfops)
#define RETURN_OPEN_NEWFOPS_NOSEM(newfops)
Functions
module_param (acq200_hostdrv_debug, int, 0644)
MODULE_PARM_DESC (acq200_hostdrv_debug,"debug level [0 = OFF]")
EXPORT_SYMBOL_GPL (acq200_hostdrv_debug)
module_param (acq200_use_interrupts, int, 0644)
MODULE_PARM_DESC (acq200_use_interrupts,"use interrupts [0 = OFF]")
module_param (acq200_debug_mbox, int, 0644)
MODULE_PARM_DESC (acq200_debug_mbox,"debug mailbox transactions [0 = OFF]")
module_param_array (slots, int, NULL, 0444)
MODULE_PARM_DESC (slots,"maps logical device# to CPCI slot#")
module_param (acq200_stub_copy_to_user, int, 0644)
MODULE_PARM_DESC (acq200_stub_copy_to_user,"profiling aid [1 = no copy]")
module_param (user_max_buf, int, 0644)
module_param (acq200_AB_dmabuf_max_order, int, 0644)
Maximum size of A,B buffers in pages.
struct Acq200Device * acq200_lookupDevice (struct device *dev)
struct Acq200Device * acq200_lookupDeviceFromClass (struct CLASS_DEVICE *dev)
static void get_max_buf (struct DmaBuf *dma_buf, int max_order)
static void alloc_max_buf (struct device *dev, struct DmaBuf *dma_buf, enum dma_data_direction dir, int max_order)
static void alloc_llhost_buf (struct device *dev, struct DmaBuf *dma_buf)
static struct Acq200Path * acq200_createPath (struct inode *inode, struct Acq200Device *device)
static void acq200_deletePath (struct Acq200Path *path)
static struct Acq200Device * acq200_lookup_device (struct inode *inode)
static int acq200_poll_response (struct Acq200Device *device, long timeout)
static void fill_ramp (int *data, int len)
static struct Acq200Device * acq200_device_create (struct pci_dev *pci_dev)
static void __kbuf_free (struct DmaBuf *dma_buf)
static void acq200_device_free (struct Acq200Device *device)
static ssize_t acq200_read (struct file *file, char *buf, size_t count, loff_t *posp)
static ssize_t acq200_write (struct file *file, const char *buf, size_t count, loff_t *posp)
static void acq200_mbox_dbg (struct MailboxControl *mbc, int read)
static int acq200_ioctl_read_mbox (struct Acq200Device *device, struct MailboxControl *mbc)
static int _acq200_ioctl_write_mbox (struct Acq200Device *device, struct MailboxControl *mbc)
static int acq200_ioctl_wbr_mbox (struct Acq200Device *device, struct MailboxControl *mbc)
write, block, read
static int acq200_mbox_ioctl (struct file *filp, unsigned long arg, int(*action)(struct Acq200Device *, struct MailboxControl *))
int acq200_ioctl (struct inode *inode, struct file *filp, unsigned int cmd, unsigned long arg)
int acq200_sendCommand (struct Acq200Device *device, u32 command)
send a command, single parameter
int acq200_sendCommandA3A4 (struct Acq200Device *device, u32 command, u32 a3, u32 a4)
send a command with A3, A4 parameters
int acq200_sendQuery (struct Acq200Device *device, unsigned command, unsigned *a1, unsigned *a2, unsigned *a3, unsigned *a4)
send a query, pick up answers for aX != NULL
int acq200_handle_incoming_message (struct Acq200Device *device)
irqreturn_t acq200_incoming_message_isr (struct Acq200Device *device)
static irqreturn_t acq200_doorbell_isr (struct Acq200Device *device, u32 doorbell)
static irqreturn_t acq200_isr (int irq, void *dev_id)
int acq200_onFirstClientOpenAB (struct Acq200Device *device)
int acq200_onLastClientReleaseAB (struct Acq200Device *device)
static int onOpen (struct Acq200Path *path)
static int onRelease (struct Acq200Path *path)
int acq200_bridge_openAB (struct inode *inode, struct file *file)
int acq200_bridge_releaseAB (struct inode *inode, struct file *file)
int acq200_ioctlAB (struct inode *inode, struct file *file, unsigned int cmd, unsigned long arg)
int acq200_open (struct inode *inode, struct file *file)
int acq200_release (struct inode *inode, struct file *file)
static int __devinit acq200_device_init (struct Acq200Device *device)
static void acq200_set_dev_type (struct Acq200Device *device, const struct pci_device_id *ent)
static int __devinit acq200_probe (struct pci_dev *dev, const struct pci_device_id *ent)
static void acq200_remove (struct pci_dev *dev)
static int __init acq200_init (void)
int acq200_init_module (void)
void acq200_exit_module (void)
module_init (acq200_init_module)
module_exit (acq200_exit_module)
MODULE_DEVICE_TABLE (pci, acq200_pci_tbl)
MODULE_LICENSE ("GPL")
MODULE_AUTHOR ("Peter.Milne@d-tacq.com")
MODULE_DESCRIPTION ("Driver for ACQ200 BRIDGE")
Variables
int acq200_hostdrv_debug = 0
int acq200_use_interrupts = 1
int acq200_debug_mbox = 0
int slots [MAXDEV] = { 0, }
int acq200_stub_copy_to_user = 0
int user_max_buf = 0x300000
int acq200_AB_dmabuf_max_order = LINUX26_MAXALLOC_PAGE_ORDER
char acq200_driver_name [] = "acq200"
Globals .
char acq200__driver_string [] = "D-TACQ intelligent data acquisition device"
char acq200__driver_version [] = "$Revision: 1.60 $ B1113"
char acq200__copyright [] = "Copyright (c) 2006/7 D-TACQ Solutions Ltd"
static struct Acq200Device * devices [MAXDEV]
static int idx
struct class * acq200_device_class
static struct pci_device_id
acq200_pci_tbl[] __devinitdata
static struct pci_driver acq200_driver
Detailed Description
core Linux 2.6.x host pci driver for D-TACQ ACQ2xx cards.
Definition in file acq200.c.
Define Documentation
#define BIGTIME 0x7fffffff
Definition at line 440 of file acq200.c.
Referenced by acq200_poll_response().
#define COMMSBUF_ORDER LINUX26_MAXALLOC_PAGE_ORDER
communications buffer must have a large minimum size.
Definition at line 304 of file acq200.c.
Referenced by acq200_device_create().
#define DEFTO HZ
parameters - useful, but beware these are global
Definition at line 272 of file acq200.c.
Referenced by acq200_sendCommand(), acq200_sendCommandA3A4(), and acq200_sendQuery().
#define EXPORT_SYMTAB
Definition at line 258 of file acq200.c.
#define IRQ_IGNORE (ACQ200_OISR_OM_0|ACQ200_OISR_OM_1)
Referenced by acq200_isr().
#define LINUX26_MAXALLOC_PAGE_ORDER 12
Definition at line 301 of file acq200.c.
#define MAXDEV 16
Definition at line 271 of file acq200.c.
Referenced by acq200_device_create().
#define MBX_READ 1
Definition at line 584 of file acq200.c.
Referenced by _acq200_ioctl_write_mbox(), and acq200_ioctl_read_mbox().
#define MYTURN 1
Definition at line 931 of file acq200.c.
#define RETURN_OPEN_NEWFOPS (newfops)
Value:
file->f_op = &newfops;                          \
        goto return_open_take_busy;
Referenced by acq200_open().
#define RETURN_OPEN_NEWFOPS_NOSEM (newfops)
Value:
file->f_op = &newfops;                          \
        goto return_open;
Referenced by acq200_open().
Function Documentation
static void __kbuf_free (struct DmaBuf * dma_buf) [static]
Definition at line 526 of file acq200.c.
References DmaBuf::order, and DmaBuf::va.
Referenced by acq200_device_free().
static int _acq200_ioctl_write_mbox (struct Acq200Device * device, struct MailboxControl * mbc) [static]
Definition at line 616 of file acq200.c.
References acq200_debug_mbox, acq200_mbox_dbg(), MBC_FROM_MBXW, MBOX_NUM, Acq200Device::mbox_sync, MBOX_WRITE, MBX_READ, MailboxControl::mbxw, and Acq200Device::MailboxSync::response_received.
Referenced by acq200_ioctl_wbr_mbox().
int acq200_bridge_openAB (struct inode * inode, struct file * file)
Definition at line 990 of file acq200.c.
References Acq200Device::AB, acq200_AB_dmabuf_max_order, alloc_max_buf(), Acq200Path::bufferMappings, copyDmaBuf2IoMapping(), DEV, onOpen(), Acq200Device::pci_dev, PD, and DmaBuf::va.
Referenced by acq200_open().
int acq200_bridge_releaseAB (struct inode * inode, struct file * file)
Definition at line 1009 of file acq200.c.
References acq200_bridge_release(), onRelease(), and PD.
Referenced by acq200_open().
static struct Acq200Path* acq200_createPath (struct inode * inode, struct Acq200Device * device) [static, read]
Definition at line 395 of file acq200.c.
References Acq200Path::device, Acq200Device::dma_buf, Acq200Path::dma_buf, Acq200Device::llhost_dma_buf, Acq200Path::llhost_dma_buf, Acq200Path::minor, PATH_HEAD, and Acq200Path::return_waitq.
Referenced by acq200_open().
static void acq200_deletePath (struct Acq200Path * path) [static]
Definition at line 413 of file acq200.c.
Referenced by acq200_release().
static struct Acq200Device* acq200_device_create (struct pci_dev * pci_dev) [static, read]
acq32 i2o buffers are acq32-side, but acq200 are host side, this is for emulation.
Definition at line 482 of file acq200.c.
References acq200_map_pci_memory(), acq200_pool_create(), acq200_streaming_isr_bh(), alloc_llhost_buf(), alloc_max_buf(), assert, Acq200Device::DevicePrivateData::aux_waitq, Acq200Device::buffer_AB_busy_mutex, Acq200Device::clients, COMMSBUF_ORDER, Acq200Device::dma_buf, dma_buf_len(), Acq200Device::LogicalDev::drv_name, fill_ramp(), Acq200Device::idx, idx, Acq200Device::ldev, Acq200Device::llhost_dma_buf, Acq200Device::m_dpd, MAXDEV, Acq200Device::mbox_sync, Acq200Device::Clients::mutex, Acq200Device::MailboxSync::mutex, DmaBuf::pa, Acq200Device::IoMapping::pa, Acq200Device::pci_dev, Acq200Device::ram, rchInit(), Acq200Device::streambuf, streamBufInit(), Acq200Device::DevicePrivateData::streaming_isr_tasklet, Acq200Device::IoMapping::va, DmaBuf::va, and Acq200Device::MailboxSync::waitq.
Referenced by acq200_probe().
static void acq200_device_free (struct Acq200Device * device) [static]
Definition at line 532 of file acq200.c.
References __kbuf_free(), Acq200Device::AB, acq200_pool_delete(), acq200_unmap_pci_memory(), Acq200Device::dma_buf, Acq200Device::llhost_dma_buf, DmaBuf::order, and DmaBuf::va.
Referenced by acq200_remove().
static int __devinit acq200_device_init (struct Acq200Device * device) [static]
Definition at line 1165 of file acq200.c.
References acq200_create_sysfs_class(), acq200_create_sysfs_device(), acq200_device_class, acq200_get_cpci_slot(), acq200_getAvailableChannels(), acq200_ioctl(), acq200_open(), acq200_release(), acq200_sendCommand(), acq200_sendCommandA3A4(), acq200_use_interrupts, Acq200Device::bkl, BP_FC_SET_HOST_DMABUF, BP_FC_SET_INTERRUPTS, BP_SET_A1, BP_SET_FUNCODE, Acq200Device::class_dev, CLASS_DEVICE_CREATE, Acq200Device::completed_onetime_setups, Acq200Device::dma_buf, dma_buf_len(), Acq200Device::LogicalDev::drv_name, err, Acq200Device::idx, info, Acq200Device::ldev, Acq200Device::BKL::lock, Acq200Device::LogicalDev::major, Acq200Device::mbox_sync, NMAPPINGS, DmaBuf::pa, Acq200Device::pci_dev, slots, and Acq200Device::MailboxSync::using_interrupt.
Referenced by acq200_probe().
static irqreturn_t acq200_doorbell_isr (struct Acq200Device * device, u32 doorbell) [static]
Definition at line 875 of file acq200.c.
References dbg, Acq200Device::LogicalDev::drv_name, Acq200Device::ldev, Acq200Device::mbox_sync, Acq200Device::MailboxSync::response_received, and Acq200Device::MailboxSync::waitq.
Referenced by acq200_isr().
void acq200_exit_module (void)
Definition at line 1353 of file acq200.c.
References acq200_device_class, and idx.
int acq200_handle_incoming_message (struct Acq200Device * device)
Definition at line 833 of file acq200.c.
References acq200_consume_i2o(), ACQ200_OQP, Acq200Device::DevicePrivateData::bad_mfa_count, CSR, dbg, and Acq200Device::m_dpd.
Referenced by i2o_missed_int_checker().
irqreturn_t acq200_incoming_message_isr (struct Acq200Device * device)
Definition at line 850 of file acq200.c.
References acq200_consume_i2o(), ACQ200_OIMR, ACQ200_OISR_OPQI, ACQ200_OQP, Acq200Device::DevicePrivateData::bad_mfa_count, BAD_MFA_THRESHOLD, CSR, dbg, err, Acq200Device::idx, Acq200Device::m_dpd, and mask.
Referenced by acq200_isr().
static int __init acq200_init (void) [static]
Definition at line 1334 of file acq200.c.
References acq200_device_class, and dbg.
Referenced by acq200_init_module().
int acq200_init_module (void)
Definition at line 1344 of file acq200.c.
References acq200__copyright, acq200__driver_string, acq200__driver_version, acq200_driver_name, acq200_init(), and info.
int acq200_ioctl (struct inode * inode, struct file * filp, unsigned int cmd, unsigned long arg)
Definition at line 730 of file acq200.c.
References acq200_intsDisable(), acq200_intsEnable(), acq200_ioctl_read_mbox(), acq200_ioctl_wbr_mbox(), acq200_mbox_ioctl(), ACQ200_MBOX_IOR, ACQ200_MBOX_IOW, ACQ200_MBOX_IOWR, ACQ32_IOG_PCIREGS_OFFSET, ACQ32_IOS_INTS_DISABLE, ACQ32_IOS_INTS_ENABLE, Acq200Device::csr, dbg, DEV, and Acq200Device::IoMapping::pa.
Referenced by acq200_device_init(), and acq200_open().
static int acq200_ioctl_read_mbox (struct Acq200Device * device, struct MailboxControl * mbc) [static]
Definition at line 597 of file acq200.c.
References acq200_debug_mbox, acq200_mbox_dbg(), MBC_FROM_MBXR, MBOX_NUM, MBOX_READ, MBX_READ, and MailboxControl::mbxr.
Referenced by acq200_ioctl(), and acq200_ioctl_wbr_mbox().
static int acq200_ioctl_wbr_mbox (struct Acq200Device * device, struct MailboxControl * mbc) [static]
write, block, read
Definition at line 649 of file acq200.c.
References _acq200_ioctl_write_mbox(), acq200_ioctl_read_mbox(), acq200_poll_response(), dbg, MailboxControl::mbc_flags, MBC_FLAGS_TO, MBC_FLAGS_TO_FOREVER, Acq200Device::mbox_sync, Acq200Device::MailboxSync::mutex, RESPONSE_RECEIVED, timeout, Acq200Device::MailboxSync::using_interrupt, and Acq200Device::MailboxSync::waitq.
Referenced by acq200_ioctl(), acq200_release(), acq200_sendCommand(), acq200_sendCommandA3A4(), and acq200_sendQuery().
int acq200_ioctlAB (struct inode * inode, struct file * file, unsigned int cmd, unsigned long arg)
Definition at line 1017 of file acq200.c.
References ACQ200_BUFFER_AB_IOWR, acq200_bufferABaction(), Acq200Device::buffer_AB_busy_mutex, BUFFERAB_OPS_SZ, COPY_FROM_USER, COPY_TO_USER, dbg, Acq200Path::device, Acq200Path::has_AB_busy_mutex, and PD.
Referenced by acq200_open().
static irqreturn_t acq200_isr (int irq, void * dev_id) [static]
clear the status bits anyway
Definition at line 888 of file acq200.c.
References acq200_doorbell_isr(), acq200_incoming_message_isr(), ACQ200_ODR, ACQ200_OISR, ACQ200_OISR_ODI, ACQ200_OISR_OPQI, CSR, dbg, Acq200Device::LogicalDev::drv_name, err, Acq200Device::interrupt_count, IRQ_IGNORE, and Acq200Device::ldev.
static struct Acq200Device* acq200_lookup_device (struct inode * inode) [static, read]
Definition at line 417 of file acq200.c.
References assert, dbg, idx, Acq200Device::ldev, and Acq200Device::LogicalDev::major.
Referenced by acq200_open().
struct Acq200Device* acq200_lookupDevice (struct device * dev) [read]
Definition at line 322 of file acq200.c.
References idx, and Acq200Device::pci_dev.
Referenced by acq200_remove(), show_available_input_channels(), show_available_output_channels(), show_buffer_AB_busy_mutex(), show_buffers(), show_cpci_slot(), show_heartbeat(), show_host_len(), show_host_pa(), show_interrupt_count(), show_llhost_len(), show_llhost_pa(), show_pool(), and show_rch_list().
struct Acq200Device* acq200_lookupDeviceFromClass (struct CLASS_DEVICE * dev) [read]
Definition at line 336 of file acq200.c.
References Acq200Device::class_dev, and idx.
Referenced by show_dev(), show_imask(), and store_imask().
static void acq200_mbox_dbg (struct MailboxControl * mbc, int read) [static]
Definition at line 586 of file acq200.c.
References info, mask, MBC_FROM_MBXR, MBC_FROM_MBXW, MailboxControl::mbxr, and MailboxControl::mbxw.
Referenced by _acq200_ioctl_write_mbox(), and acq200_ioctl_read_mbox().
static int acq200_mbox_ioctl (struct file * filp, unsigned long arg, int(*)(struct Acq200Device *, struct MailboxControl *) action) [static]
deferred action.
Definition at line 692 of file acq200.c.
References action(), dbg, DEV, err, MailboxControl::mbc_flags, MBC_FLAGS_ONRELEASE, Acq200Path::mbc_on_release, and PD.
Referenced by acq200_ioctl().
int acq200_onFirstClientOpenAB (struct Acq200Device * device)
Definition at line 933 of file acq200.c.
References Acq200Device::i2o_backstop, i2o_missed_int_checker(), and Acq200Device::idx.
Referenced by onOpen().
int acq200_onLastClientReleaseAB (struct Acq200Device * device)
Definition at line 947 of file acq200.c.
References Acq200Device::i2o_backstop.
Referenced by onRelease().
int acq200_open (struct inode * inode, struct file * file)
Definition at line 1050 of file acq200.c.
References acq200_bridge_openAB(), acq200_bridge_read(), acq200_bridge_readAB(), acq200_bridge_release(), acq200_bridge_releaseAB(), acq200_bridge_write(), acq200_createPath(), acq200_ioctl(), acq200_ioctlAB(), acq200_lookup_device(), acq200_mmap_host(), acq200_mmap_llhost(), acq200_mmap_mbox(), acq200_mmapAB(), acq200_read(), acq200_release(), acq200_write(), BIGDUMPDEV, Acq200Device::buffer_AB_busy_mutex, dbg, DEVRAW, Acq200Path::has_AB_busy_mutex, IS_CHANNEL_DEV, IS_FILE, IS_RSH, LLHOSTDEV, Acq200Path::minor, RETURN_OPEN_NEWFOPS, RETURN_OPEN_NEWFOPS_NOSEM, and SET_PATH.
Referenced by acq200_device_init().
static int acq200_poll_response (struct Acq200Device * device, long timeout) [static]
Definition at line 442 of file acq200.c.
References BIGTIME, BP_CI_ACK, BP_MB_COMMAND, dbg, mask, MBOX, and timeout.
Referenced by acq200_ioctl_wbr_mbox().
static int __devinit acq200_probe (struct pci_dev * dev, const struct pci_device_id * ent) [static]
Definition at line 1272 of file acq200.c.
References acq200_device_create(), acq200_device_init(), and acq200_set_dev_type().
static ssize_t acq200_read (struct file * file, char * buf, size_t count, loff_t * posp) [static]
Definition at line 546 of file acq200.c.
References DEV, Acq200Device::dma_buf, err, DmaBuf::order, ORDER2LEN, and DmaBuf::pa.
Referenced by acq200_open().
int acq200_release (struct inode * inode, struct file * file)
Definition at line 1146 of file acq200.c.
References acq200_deletePath(), acq200_ioctl_wbr_mbox(), Acq200Device::buffer_AB_busy_mutex, dbg, DEV, Acq200Path::device, Acq200Path::has_AB_busy_mutex, MailboxControl::mbc_flags, MBC_FLAGS_ONRELEASE, Acq200Path::mbc_on_release, and PD.
Referenced by acq200_bridge_release_generic(), acq200_bridge_release_message(), acq200_device_init(), and acq200_open().
static void acq200_remove (struct pci_dev * dev) [static]
Definition at line 1281 of file acq200.c.
References acq200_device_class, acq200_device_free(), acq200_lookupDevice(), acq200_remove_sysfs_class(), acq200_remove_sysfs_device(), dbg, Acq200Device::LogicalDev::drv_name, Acq200Device::idx, Acq200Device::ldev, Acq200Device::LogicalDev::major, Acq200Device::mbox_sync, Acq200Device::pci_dev, and Acq200Device::MailboxSync::using_interrupt.
int acq200_sendCommand (struct Acq200Device * device, u32 command)
send a command, single parameter
Definition at line 764 of file acq200.c.
References acq200_ioctl_wbr_mbox(), BP_CI_COMMAND, BP_CI_DONE, BP_MB_COMMAND, DEFTO, MailboxControl::mbc_flags, MBC_TO_MBXR, MBC_TO_MBXW, and MailboxControl::mbxw.
Referenced by acq200_device_init().
int acq200_sendCommandA3A4 (struct Acq200Device * device, u32 command, u32 a3, u32 a4)
send a command with A3, A4 parameters
send a command, single parameter
Definition at line 775 of file acq200.c.
References acq200_ioctl_wbr_mbox(), BP_CI_COMMAND, BP_CI_DONE, BP_MB_A3, BP_MB_A4, BP_MB_COMMAND, DEFTO, MailboxControl::mbc_flags, MBC_TO_MBXR, MBC_TO_MBXW, and MailboxControl::mbxw.
Referenced by acq200_device_init().
int acq200_sendQuery (struct Acq200Device * device, unsigned command, unsigned * a1, unsigned * a2, unsigned * a3, unsigned * a4)
send a query, pick up answers for aX != NULL
Definition at line 793 of file acq200.c.
References acq200_ioctl_wbr_mbox(), BP_CI_DONE, BP_CI_QUERY, BP_GET_A1, BP_GET_A2, BP_MB_A3, BP_MB_A4, BP_MB_COMMAND, DEFTO, MailboxControl::mbc_flags, MBC_TO_MBXR, MBC_TO_MBXW, MailboxControl::mbxr, MailboxControl::mbxw, NULL_A3, and NULL_A4.
Referenced by acq200_getAvailableChannels().
static void acq200_set_dev_type (struct Acq200Device * device, const struct pci_device_id * ent) [static]
Definition at line 1258 of file acq200.c.
References Acq200Device::card_type, DEV_TYPE_ACQ196, DEV_TYPE_ACQ216, IS_ACQ196, and Acq200Device::model_name.
Referenced by acq200_probe().
static ssize_t acq200_write (struct file * file, const char * buf, size_t count, loff_t * posp) [static]
Definition at line 573 of file acq200.c.
References dbg.
Referenced by acq200_open().
static void alloc_llhost_buf (struct device * dev, struct DmaBuf * dma_buf) [static]
Definition at line 383 of file acq200.c.
References DmaBuf::order, DmaBuf::pa, and DmaBuf::va.
Referenced by acq200_device_create().
static void alloc_max_buf (struct device * dev, struct DmaBuf * dma_buf, enum dma_data_direction dir, int max_order) [static]
Definition at line 372 of file acq200.c.
References dma_buf_len(), get_max_buf(), DmaBuf::pa, and DmaBuf::va.
Referenced by acq200_bridge_openAB(), and acq200_device_create().
EXPORT_SYMBOL_GPL (acq200_hostdrv_debug)
static void fill_ramp (int * data, int len) [static]
Definition at line 469 of file acq200.c.
References idx.
Referenced by acq200_device_create().
static void get_max_buf (struct DmaBuf * dma_buf, int max_order) [static]
Definition at line 351 of file acq200.c.
References assert, dbg, DmaBuf::order, ORDER2LEN, and DmaBuf::va.
Referenced by alloc_max_buf().
MODULE_AUTHOR ("Peter.Milne@d-tacq.com")
MODULE_DESCRIPTION ("Driver for ACQ200 BRIDGE")
MODULE_DEVICE_TABLE (pci , acq200_pci_tbl)
module_exit (acq200_exit_module)
module_init (acq200_init_module)
MODULE_LICENSE ("GPL")
module_param (acq200_AB_dmabuf_max_order , int , 0644)
Maximum size of A,B buffers in pages.
May reduce for lower latency
module_param (acq200_debug_mbox , int , 0644)
module_param (acq200_use_interrupts , int , 0644)
module_param (acq200_hostdrv_debug , int , 0644)
module_param (acq200_stub_copy_to_user , int , 0644)
module_param (user_max_buf , int , 0644)
module_param_array (slots , int , NULL , 0444)
MODULE_PARM_DESC (acq200_stub_copy_to_user , "profiling aid " [1=no copy])
MODULE_PARM_DESC (acq200_use_interrupts , "use interrupts " [0=OFF])
MODULE_PARM_DESC (acq200_hostdrv_debug , "debug level " [0=OFF])
MODULE_PARM_DESC (slots , "maps logical device# to CPCI slot#")
MODULE_PARM_DESC (acq200_debug_mbox , "debug mailbox transactions " [0=OFF])
static int onOpen (struct Acq200Path * path) [static]
Definition at line 953 of file acq200.c.
References acq200_onFirstClientOpenAB(), Acq200Device::clients, Acq200Device::Clients::count, Acq200Path::device, and Acq200Device::Clients::mutex.
Referenced by acq200_bridge_openAB().
static int onRelease (struct Acq200Path * path) [static]
Definition at line 969 of file acq200.c.
References acq200_onLastClientReleaseAB(), Acq200Device::clients, Acq200Device::Clients::count, dbg, Acq200Path::device, err, and Acq200Device::Clients::mutex.
Referenced by acq200_bridge_releaseAB().
Variable Documentation
struct pci_device_id acq200_pci_tbl [] __devinitdata [static]
Initial value:
 {
        {PCI_VENDOR_ID_HINT, 0x0029, PCI_ANY_ID, PCI_ANY_ID, 0, 0, 0},
        {PCI_VENDOR_ID_INTEL, 0x0318, PCI_ANY_ID, PCI_ANY_ID, 0, 0, 0},
        {PCI_VENDOR_ID_INTEL, 0x0319, PCI_ANY_ID, PCI_ANY_ID, 0, 0, 0},
        { }
}
Definition at line 1311 of file acq200.c.
char acq200__copyright[] = "Copyright (c) 2006/7 D-TACQ Solutions Ltd"
Definition at line 315 of file acq200.c.
Referenced by acq200_init_module().
char acq200__driver_string[] = "D-TACQ intelligent data acquisition device"
Definition at line 313 of file acq200.c.
Referenced by acq200_init_module().
char acq200__driver_version[] = "$Revision: 1.60 $ B1113"
Definition at line 314 of file acq200.c.
Referenced by acq200_init_module().
int acq200_AB_dmabuf_max_order = LINUX26_MAXALLOC_PAGE_ORDER
Definition at line 306 of file acq200.c.
Referenced by acq200_bridge_openAB().
int acq200_debug_mbox = 0
Definition at line 285 of file acq200.c.
Referenced by _acq200_ioctl_write_mbox(), and acq200_ioctl_read_mbox().
struct class* acq200_device_class
Definition at line 320 of file acq200.c.
Referenced by acq200_device_init(), acq200_exit_module(), acq200_init(), and acq200_remove().
struct pci_driver acq200_driver [static]
Initial value:
 {
        .name     = acq200_driver_name,
        .id_table = acq200_pci_tbl,
        .probe    = acq200_probe,
        .remove   = __devexit_p(acq200_remove),
}
Definition at line 1317 of file acq200.c.
char acq200_driver_name[] = "acq200"
Globals .
. keep to a minimum!
Definition at line 312 of file acq200.c.
Referenced by acq200_init_module().
int acq200_hostdrv_debug = 0
Definition at line 276 of file acq200.c.
int acq200_stub_copy_to_user = 0
Definition at line 293 of file acq200.c.
Referenced by acq200_copy_from_io_to_user().
int acq200_use_interrupts = 1
Definition at line 281 of file acq200.c.
Referenced by acq200_device_init().
struct Acq200Device* devices[MAXDEV] [static]
Definition at line 316 of file acq200.c.
int idx [static]
Definition at line 317 of file acq200.c.
Referenced by acq200_device_create(), acq200_exit_module(), acq200_lookup_device(), acq200_lookupDevice(), acq200_lookupDeviceFromClass(), and fill_ramp().
int slots[MAXDEV] = { 0, }
Definition at line 289 of file acq200.c.
Referenced by acq200_device_init().
int user_max_buf = 0x300000
Definition at line 298 of file acq200.c.
Referenced by acq200_bridge_readAB(), and acq200_bufferAB_queue().