ACQ200 HOSTDRV: acq200_bigbuf_alloc.c File Reference
acq200_bigbuf_alloc.c File Reference
buffer pool
#include <linux/fs.h>
#include <linux/errno.h>
#include <linux/types.h>
#include <linux/proc_fs.h>
#include <linux/fcntl.h>
#include <linux/pci.h>
#include <linux/time.h>
#include <linux/interrupt.h>
#include <asm/io.h>
#include <asm/uaccess.h>
#include <asm/system.h>
#include <asm/segment.h>
#include "acq200.h"
#include "acq200_debug.h"
#include "rch.h"
Data Structures
struct PoolEntry
struct BigBufPool
struct BigBufPool::Pool
Defines
#define NDATAMAPPING (NMAPPINGS-1)
#define MSG_MAPPING (NMAPPINGS-1)
#define NHANDLERS 16
#define HANDLERS_SIZE (sizeof(struct ReturnCommandHandler)*NHANDLERS)
#define INCR(ibuf) (ibuf >= this_pool->max_entries-1? 0: ibuf+1)
#define FFMT "%20s: "
#define STAPRINT(fmt, field) len += sprintf(buf+len, FFMT fmt "\n", #field, field)
Functions
static void create_dev_sysfs (struct device *dev)
static void remove_dev_sysfs (struct device *dev)
static void _create_mappings (struct Acq200Device *device, struct BigBufPool *pool)
static void _delete_mappings (struct Acq200Device *device)
static void _create_handlers (struct Acq200Device *device, struct BigBufPool *pool)
static void _delete_handlers (struct Acq200Device *device)
void acq200_pool_create (struct Acq200Device *device)
void acq200_pool_delete (struct Acq200Device *device)
static void * _alloc (struct BigBufPool *big_pool, struct Pool *this_pool)
static void _free (struct BigBufPool *big_pool, struct Pool *this_pool, void *item)
struct IoMapping * acq200_pool_alloc_mapping (struct Acq200Device *device, int direction)
void acq200_pool_free_mapping (struct Acq200Device *device, struct IoMapping *mapping)
struct ReturnCommandHandler * acq200_pool_alloc_rch (struct Acq200Device *device)
void acq200_pool_free_rch (struct Acq200Device *device, struct ReturnCommandHandler *h)
static ssize_t show_pool (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (pool, S_IRUGO, show_pool, 0)
static ssize_t show_rch_list (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (rch_list, S_IRUGO, show_rch_list, 0)
Detailed Description
buffer pool
Definition in file acq200_bigbuf_alloc.c.
Define Documentation
#define FFMT "%20s: "
#define HANDLERS_SIZE (sizeof(struct ReturnCommandHandler)*NHANDLERS)
Definition at line 52 of file acq200_bigbuf_alloc.c.
Referenced by _create_handlers().
#define INCR (ibuf) (ibuf >= this_pool->max_entries-1? 0: ibuf+1)
Referenced by _alloc().
#define MSG_MAPPING (NMAPPINGS-1)
Definition at line 48 of file acq200_bigbuf_alloc.c.
Referenced by acq200_pool_create().
#define NDATAMAPPING (NMAPPINGS-1)
Definition at line 46 of file acq200_bigbuf_alloc.c.
#define NHANDLERS 16
Definition at line 50 of file acq200_bigbuf_alloc.c.
Referenced by _create_handlers().
#define STAPRINT (fmt, field) len += sprintf(buf+len, FFMT fmt "\n", #field, field)
Function Documentation
static void* _alloc (struct BigBufPool * big_pool, struct Pool * this_pool) [static]
Definition at line 179 of file acq200_bigbuf_alloc.c.
References INCR, info, PoolEntry::item, PoolEntry::reserved, and BigBufPool::sleepq.
Referenced by acq200_pool_alloc_mapping(), and acq200_pool_alloc_rch().
static void _create_handlers (struct Acq200Device * device, struct BigBufPool * pool) [static]
Definition at line 113 of file acq200_bigbuf_alloc.c.
References assert, BigBufPool::Pool::cursor, BigBufPool::Pool::entries, BigBufPool::handlers, HANDLERS_SIZE, PoolEntry::item, KMALLOC, BigBufPool::Pool::max_entries, BigBufPool::Pool::name, NHANDLERS, rchInit(), and PoolEntry::reserved.
Referenced by acq200_pool_create().
static void _create_mappings (struct Acq200Device * device, struct BigBufPool * pool) [static]
Definition at line 71 of file acq200_bigbuf_alloc.c.
References assert, BigBufPool::Pool::cursor, Acq200Device::dma_buf, dma_buf_len(), BigBufPool::Pool::entries, Acq200Device::idx, PoolEntry::item, KMALLOC, BigBufPool::mappings, BigBufPool::Pool::max_entries, BigBufPool::Pool::name, NMAPPINGS, DmaBuf::pa, PoolEntry::reserved, and DmaBuf::va.
Referenced by acq200_pool_create().
static void _delete_handlers (struct Acq200Device * device) [static]
Definition at line 141 of file acq200_bigbuf_alloc.c.
References BigBufPool::Pool::entries, BigBufPool::handlers, PoolEntry::item, KFREE, and Acq200Device::pool.
Referenced by acq200_pool_delete().
static void _delete_mappings (struct Acq200Device * device) [static]
Definition at line 107 of file acq200_bigbuf_alloc.c.
References BigBufPool::Pool::entries, PoolEntry::item, KFREE, BigBufPool::mappings, and Acq200Device::pool.
Referenced by acq200_pool_delete().
static void _free (struct BigBufPool * big_pool, struct Pool * this_pool, void * item) [static]
Definition at line 204 of file acq200_bigbuf_alloc.c.
References err, PoolEntry::reserved, and BigBufPool::sleepq.
Referenced by acq200_pool_free_mapping(), and acq200_pool_free_rch().
struct IoMapping* acq200_pool_alloc_mapping (struct Acq200Device * device, int direction) [read]
Definition at line 225 of file acq200_bigbuf_alloc.c.
References _alloc(), dbg, BigBufPool::mappings, and Acq200Device::pool.
Referenced by acq200_bridge_read_generic(), and acq200_bridge_write_generic().
struct ReturnCommandHandler* acq200_pool_alloc_rch (struct Acq200Device * device) [read]
Definition at line 243 of file acq200_bigbuf_alloc.c.
References _alloc(), dbg, BigBufPool::handlers, and Acq200Device::pool.
Referenced by acq200_bridge_read_generic(), acq200_bridge_release_message(), acq200_bridge_write_generic(), and acq200_bufferAB_queue().
void acq200_pool_create (struct Acq200Device * device)
Definition at line 148 of file acq200_bigbuf_alloc.c.
References _create_handlers(), _create_mappings(), create_dev_sysfs(), BigBufPool::Pool::entries, KMALLOC, BigBufPool::mappings, MSG_MAPPING, Acq200Device::pci_dev, Acq200Device::pool, PoolEntry::reserved, and BigBufPool::sleepq.
Referenced by acq200_device_create().
void acq200_pool_delete (struct Acq200Device * device)
Definition at line 164 of file acq200_bigbuf_alloc.c.
References _delete_handlers(), _delete_mappings(), KFREE, Acq200Device::pci_dev, Acq200Device::pool, and remove_dev_sysfs().
Referenced by acq200_device_free().
void acq200_pool_free_mapping (struct Acq200Device * device, struct IoMapping * mapping)
Definition at line 236 of file acq200_bigbuf_alloc.c.
References _free(), dbg, BigBufPool::mappings, and Acq200Device::pool.
Referenced by acq200_bridge_read_generic(), and i2o_recycleRch().
void acq200_pool_free_rch (struct Acq200Device * device, struct ReturnCommandHandler * h)
Definition at line 253 of file acq200_bigbuf_alloc.c.
References _free(), dbg, BigBufPool::handlers, and Acq200Device::pool.
Referenced by i2o_recycleRch().
static void create_dev_sysfs (struct device * dev) [static]
Definition at line 338 of file acq200_bigbuf_alloc.c.
References DEVICE_CREATE_FILE.
Referenced by acq200_pool_create().
static DEVICE_ATTR (pool , S_IRUGO , show_pool , 0) [static]
static DEVICE_ATTR (rch_list , S_IRUGO , show_rch_list , 0) [static]
static void remove_dev_sysfs (struct device * dev) [static]
Definition at line 344 of file acq200_bigbuf_alloc.c.
Referenced by acq200_pool_delete().
static ssize_t show_pool (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 262 of file acq200_bigbuf_alloc.c.
References acq200_lookupDevice(), BigBufPool::Pool::cursor, BigBufPool::Pool::entries, ReturnCommandHandler::handler, BigBufPool::handlers, PoolEntry::item, RchReturn::kbuf, BigBufPool::mappings, BigBufPool::Pool::max_entries, Acq200Device::pool, ReturnCommandHandler::rchReturn, PoolEntry::reserved, and RchReturn::valid.
static ssize_t show_rch_list (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 310 of file acq200_bigbuf_alloc.c.
References acq200_lookupDevice(), ReturnCommandHandler::handler, RchReturn::kbuf, ReturnCommandHandler::list, Acq200Device::DevicePrivateData::rch::list, Acq200Device::m_dpd, ReturnCommandHandler::path, Acq200Device::DevicePrivateData::rch, ReturnCommandHandler::rchReturn, and RchReturn::valid.