ACQ200 HOSTDRV: acq200_mmap.c File Reference
acq200_mmap.c File Reference
#include <linux/kernel.h>
#include <linux/pci.h>
#include <linux/time.h>
#include <linux/interrupt.h>
#include <linux/init.h>
#include <linux/timex.h>
#include <linux/vmalloc.h>
#include <linux/mm.h>
#include <linux/moduleparam.h>
#include <linux/proc_fs.h>
#include <asm/pgtable.h>
#include <asm/uaccess.h>
#include "acq200_debug.h"
#include "acq200.h"
#include "acq200_minors.h"
Defines
#define PCI_BA_CSR 0
#define CSR_SIZE 0x80
#define CSR_SIZE_MAX 0x1000
#define BA_MASK PCI_BASE_ADDRESS_MEM_MASK
Functions
static int acq200_makeIoMapping (struct Acq200Device *device, int bar, const char *ident, int len)
int acq200_map_pci_memory (struct Acq200Device *device)
map remote regs area on device load
static void clearIoMapping (struct IoMapping *iomap)
void acq200_unmap_pci_memory (struct Acq200Device *device)
unmap remote regs are on device unload
static int getDirectionFromVma (struct vm_area_struct *vma)
static int mmap_dmabuf (struct file *file, struct vm_area_struct *vma, struct DmaBuf *dma_buf, char id)
int acq200_mmap_host (struct file *file, struct vm_area_struct *vma)
mmap the host buffer.
int acq200_mmap_llhost (struct file *file, struct vm_area_struct *vma)
mmap the host buffer.
int acq200_mmapAB (struct file *file, struct vm_area_struct *vma)
provide user mapping to mailboxes on target.
int acq200_mmap_mbox (struct file *file, struct vm_area_struct *vma)
provide user mapping to mailboxes on target.
Define Documentation
#define BA_MASK PCI_BASE_ADDRESS_MEM_MASK
Referenced by acq200_makeIoMapping().
#define CSR_SIZE 0x80
Definition at line 44 of file acq200_mmap.c.
Referenced by acq200_map_pci_memory().
#define CSR_SIZE_MAX 0x1000
Definition at line 45 of file acq200_mmap.c.
Referenced by acq200_mmap_mbox().
#define PCI_BA_CSR 0
Definition at line 43 of file acq200_mmap.c.
Referenced by acq200_map_pci_memory().
Function Documentation
static int acq200_makeIoMapping (struct Acq200Device * device, int bar, const char * ident, int len) [static]
Definition at line 47 of file acq200_mmap.c.
References BA_MASK, Acq200Device::csr, dbg, Acq200Device::LogicalDev::drv_name, Acq200Device::ldev, and Acq200Device::pci_dev.
Referenced by acq200_map_pci_memory().
int acq200_map_pci_memory (struct Acq200Device * device)
map remote regs area on device load
provide user mapping to mailboxes on target
Definition at line 78 of file acq200_mmap.c.
References acq200_makeIoMapping(), CSR_SIZE, and PCI_BA_CSR.
Referenced by acq200_device_create().
int acq200_mmap_host (struct file * file, struct vm_area_struct * vma)
mmap the host buffer.
Definition at line 159 of file acq200_mmap.c.
References mmap_dmabuf(), and PD.
Referenced by acq200_open().
int acq200_mmap_llhost (struct file * file, struct vm_area_struct * vma)
mmap the host buffer.
Definition at line 167 of file acq200_mmap.c.
References mmap_dmabuf(), and PD.
Referenced by acq200_open().
int acq200_mmap_mbox (struct file * file, struct vm_area_struct * vma)
provide user mapping to mailboxes on target.
follows LDD3.pg429
Definition at line 187 of file acq200_mmap.c.
References Acq200Device::csr, CSR_SIZE_MAX, DEV, Acq200Device::IoMapping::pa, and STATUS.
Referenced by acq200_open().
int acq200_mmapAB (struct file * file, struct vm_area_struct * vma)
provide user mapping to mailboxes on target.
mmap the host buffer.
follows LDD3.pg429
Definition at line 175 of file acq200_mmap.c.
References Acq200Device::AB, DEV, mmap_dmabuf(), and PD.
Referenced by acq200_open().
void acq200_unmap_pci_memory (struct Acq200Device * device)
unmap remote regs are on device unload
map remote regs area on device load
Definition at line 102 of file acq200_mmap.c.
References clearIoMapping(), and Acq200Device::csr.
Referenced by acq200_device_free().
static void clearIoMapping (struct IoMapping * iomap) [static]
Definition at line 91 of file acq200_mmap.c.
Referenced by acq200_unmap_pci_memory().
static int getDirectionFromVma (struct vm_area_struct * vma) [inline, static]
Definition at line 111 of file acq200_mmap.c.
static int mmap_dmabuf (struct file * file, struct vm_area_struct * vma, struct DmaBuf * dma_buf, char id) [static]
Definition at line 136 of file acq200_mmap.c.
References dbg, dma_buf_len(), DmaBuf::pa, and STATUS.
Referenced by acq200_mmap_host(), acq200_mmap_llhost(), and acq200_mmapAB().