ACQ200 HOSTDRV: acq200_if.c File Reference
acq200_if.c File Reference
interface layer for acq200 peripheral.
#include <linux/ctype.h>
#include <linux/kernel.h>
#include <linux/pci.h>
#include <linux/time.h>
#include <linux/interrupt.h>
#include <linux/init.h>
#include <linux/timex.h>
#include <linux/vmalloc.h>
#include <linux/mm.h>
#include <linux/moduleparam.h>
#include <linux/proc_fs.h>
#include <asm/uaccess.h>
#include <asm/apic.h>
#include "acq200_debug.h"
#include "acq200.h"
#include "acq200_minors.h"
Functions
static ssize_t show_heartbeat (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (heartbeat, S_IRUGO, show_heartbeat, 0)
int acq200_get_cpci_slot (struct pci_dev *pci_dev)
static ssize_t show_cpci_slot (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (cpci_slot, S_IRUGO, show_cpci_slot, 0)
static ssize_t show_buffer_AB_busy_mutex (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (buffer_AB_busy_mutex, S_IRUGO, show_buffer_AB_busy_mutex, 0)
static ssize_t show_interrupt_count (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (interrupt_count, S_IRUGO, show_interrupt_count, 0)
static ssize_t show_host_pa (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (host_pa, S_IRUGO, show_host_pa, 0)
static ssize_t show_host_len (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (host_len, S_IRUGO, show_host_len, 0)
static ssize_t show_llhost_pa (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (llhost_pa, S_IRUGO, show_llhost_pa, 0)
static ssize_t show_llhost_len (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (llhost_len, S_IRUGO, show_llhost_len, 0)
static ssize_t show_available_input_channels (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (available_input_channels, S_IRUGO, show_available_input_channels, 0)
static ssize_t show_available_output_channels (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (available_output_channels, S_IRUGO, show_available_output_channels, 0)
static ssize_t dumpDmaBuf (struct DmaBuf *dma_buf, char *buf, int maxbuf, const char *id)
static ssize_t show_buffers (struct device *dev, struct device_attribute *attr, char *buf)
static DEVICE_ATTR (buffers, S_IRUGO, show_buffers, 0)
void acq200_device_create_file (struct device *dev, struct device_attribute *attr, const char *file, int line)
void acq200_create_sysfs_device (struct device *dev)
void acq200_remove_sysfs_device (struct device *dev)
static ssize_t show_imask (struct CLASS_DEVICE *dev, struct device_attribute *attr, char *buf)
static ssize_t store_imask (struct CLASS_DEVICE *dev, struct device_attribute *attr, const char *buf, size_t count)
static CLASS_DEVICE_ATTR (imask, S_IRUGO|S_IWUSR, show_imask, store_imask)
static ssize_t show_dev (struct CLASS_DEVICE *dev, struct device_attribute *attr, char *buf)
static CLASS_DEVICE_ATTR (dev, S_IRUGO, show_dev, 0)
void acq200_create_sysfs_class (struct Acq200Device *adev)
void acq200_remove_sysfs_class (struct Acq200Device *adev)
Detailed Description
interface layer for acq200 peripheral.
Definition in file acq200_if.c.
Function Documentation
void acq200_create_sysfs_class (struct Acq200Device * adev)
Definition at line 417 of file acq200_if.c.
References Acq200Device::class_dev, dbg, DEVICE_CREATE_FILE, err, and Acq200Device::pci_dev.
Referenced by acq200_device_init().
void acq200_create_sysfs_device (struct device * dev)
Definition at line 280 of file acq200_if.c.
References dbg, and DEVICE_CREATE_FILE.
Referenced by acq200_device_init().
void acq200_device_create_file (struct device * dev, struct device_attribute * attr, const char * file, int line)
Definition at line 270 of file acq200_if.c.
References err.
int acq200_get_cpci_slot (struct pci_dev * pci_dev)
Definition at line 74 of file acq200_if.c.
Referenced by acq200_device_init(), and show_cpci_slot().
void acq200_remove_sysfs_class (struct Acq200Device * adev)
Definition at line 437 of file acq200_if.c.
References Acq200Device::class_dev.
Referenced by acq200_remove().
void acq200_remove_sysfs_device (struct device * dev)
Definition at line 298 of file acq200_if.c.
Referenced by acq200_remove().
static CLASS_DEVICE_ATTR (dev , S_IRUGO , show_dev , 0) [static]
static CLASS_DEVICE_ATTR (imask , S_IRUGO| S_IWUSR, show_imask , store_imask) [static]
static DEVICE_ATTR (interrupt_count , S_IRUGO , show_interrupt_count , 0) [static]
static DEVICE_ATTR (llhost_len , S_IRUGO , show_llhost_len , 0) [static]
static DEVICE_ATTR (cpci_slot , S_IRUGO , show_cpci_slot , 0) [static]
static DEVICE_ATTR (available_input_channels , S_IRUGO , show_available_input_channels , 0) [static]
static DEVICE_ATTR (host_pa , S_IRUGO , show_host_pa , 0) [static]
static DEVICE_ATTR (available_output_channels , S_IRUGO , show_available_output_channels , 0) [static]
static DEVICE_ATTR (host_len , S_IRUGO , show_host_len , 0) [static]
static DEVICE_ATTR (buffers , S_IRUGO , show_buffers , 0) [static]
static DEVICE_ATTR (heartbeat , S_IRUGO , show_heartbeat , 0) [static]
static DEVICE_ATTR (llhost_pa , S_IRUGO , show_llhost_pa , 0) [static]
static DEVICE_ATTR (buffer_AB_busy_mutex , S_IRUGO , show_buffer_AB_busy_mutex , 0) [static]
static ssize_t dumpDmaBuf (struct DmaBuf * dma_buf, char * buf, int maxbuf, const char * id) [static]
Definition at line 242 of file acq200_if.c.
References dma_buf_len(), DmaBuf::order, DmaBuf::pa, and DmaBuf::va.
Referenced by show_buffers().
static ssize_t show_available_input_channels (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 206 of file acq200_if.c.
References acq200_lookupDevice(), Acq200Device::input_channels, and Acq200Device::CHANNEL_INFO::nchannels.
static ssize_t show_available_output_channels (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 224 of file acq200_if.c.
References acq200_lookupDevice(), Acq200Device::CHANNEL_INFO::nchannels, and Acq200Device::output_channels.
static ssize_t show_buffer_AB_busy_mutex (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 101 of file acq200_if.c.
References acq200_lookupDevice(), and Acq200Device::buffer_AB_busy_mutex.
static ssize_t show_buffers (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 251 of file acq200_if.c.
References Acq200Device::AB, acq200_lookupDevice(), Acq200Device::dma_buf, dumpDmaBuf(), and DmaBuf::va.
static ssize_t show_cpci_slot (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 84 of file acq200_if.c.
References acq200_get_cpci_slot(), acq200_lookupDevice(), and Acq200Device::pci_dev.
static ssize_t show_dev (struct CLASS_DEVICE * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 368 of file acq200_if.c.
References acq200_lookupDeviceFromClass(), Acq200Device::ldev, and Acq200Device::LogicalDev::major.
static ssize_t show_heartbeat (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 46 of file acq200_if.c.
References acq200_getHeartbeat(), and acq200_lookupDevice().
static ssize_t show_host_len (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 157 of file acq200_if.c.
References acq200_lookupDevice(), Acq200Device::dma_buf, and dma_buf_len().
static ssize_t show_host_pa (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 141 of file acq200_if.c.
References acq200_lookupDevice(), Acq200Device::dma_buf, and DmaBuf::pa.
static ssize_t show_imask (struct CLASS_DEVICE * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 316 of file acq200_if.c.
References acq200_lookupDeviceFromClass(), and Acq200Device::imask.
static ssize_t show_interrupt_count (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 121 of file acq200_if.c.
References acq200_lookupDevice(), and Acq200Device::interrupt_count.
static ssize_t show_llhost_len (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 189 of file acq200_if.c.
References acq200_lookupDevice(), dma_buf_len(), and Acq200Device::llhost_dma_buf.
static ssize_t show_llhost_pa (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 173 of file acq200_if.c.
References acq200_lookupDevice(), Acq200Device::llhost_dma_buf, and DmaBuf::pa.
static ssize_t store_imask (struct CLASS_DEVICE * dev, struct device_attribute * attr, const char * buf, size_t count) [static]
Definition at line 332 of file acq200_if.c.
References acq200_bkl(), acq200_intsMask(), acq200_lookupDeviceFromClass(), BKL_LOCK, BKL_QUERY, BKL_UNLOCK, and Acq200Device::imask.