ACQ200 HOSTDRV: acq200.h File Reference
acq200.h File Reference
internal header file for acq200 Linux PCI host driver.
#include <linux/list.h>
#include <linux/kthread.h>
#include <linux/version.h>
#include <linux/spinlock.h>
#include "streambuf.h"
#include "acq200_ioctl.h"
Data Structures
struct RchReturn
struct ReturnCommandHandler
struct DmaBuf
struct Acq200Device
device descriptor, one per device
struct Acq200Device::LogicalDev
struct Acq200Device::IoMapping
struct Acq200Device::MailboxSync
struct Acq200Device::Clients
struct Acq200Device::CHANNEL_INFO
struct Acq200Device::DevicePrivateData
struct Acq200Device::DevicePrivateData::rch
struct Acq200Device::BKL
struct Acq200Path
path descriptor, one per open path
Defines
#define CLASS_DEVICE device
#define CLASS_DEVICE_CREATE device_create
#define CLASS_DEVICE_ATTR DEVICE_ATTR
#define CLASS_DEVICE_CREATE_FILE DEVICE_CREATE_FILE
#define NMAPPINGS 4
#define IS_ACQ196(ent) ((ent)->vendor == PCI_VENDOR_ID_INTEL)
#define DEV_TYPE_ACQ32 0x0100
#define DEV_TYPE_ACQ16 0x0200
#define DEV_TYPE_ACQ196 0x1000
#define DEV_TYPE_ACQ164 0x1100
#define DEV_TYPE_WAV232 0x2000
#define DEV_TYPE_ACQ216 0x2100
#define RCH_KB_POOL 1
#define MK_DMABUF_OFFSET(kbuf, device) (kbuf->pa & PCI_WINDOW_MASK(&device->dma_buf))
#define USE_POOL 0
#define ORDER2LEN(order) ((1<<(order)) * PAGE_SIZE)
#define KNAME 32
#define BAD_MFA_THRESHOLD 100
#define ACQ200_MAILBOX_0 0x10
#define ACQ200_ODR 0x2c
#define ACQ200_OISR 0x30
#define ACQ200_OIMR 0x34
#define ACQ200_IQP 0x40
#define ACQ200_OQP 0x44
#define ACQ200_OISR_OM_0 0x01
#define ACQ200_OISR_OM_1 0x02
#define ACQ200_OISR_ODI 0x04
#define ACQ200_OISR_OPQI 0x08
#define ACQ200_OISR_PCI_INTA 0x10
#define PCI_I2O_INVALID_MFA 0xffffffff
#define CSR(dev, byte_off) ((dev)->csr.va+(byte_off)/4)
#define RESPONSE_RECEIVED(dev) ((dev)->mbox_sync.response_received != 0)
#define PATH_HEAD (offsetof(struct Acq200Path, scratch))
#define LDH_OUTBOUND 1
last_direction_hack args
#define LDH_INBOUND -1
#define LDH_NONE 0
#define ACQ200_ON_OPEN(inode, file)
#define ACQ200_ON_CLOSE(file)
#define MBOX_OFFSET 0x10
#define MBOX_OFFSETL (MBOX_OFFSET/sizeof(u32))
#define MBOX(device, ibox) (device->csr.va[MBOX_OFFSETL+(ibox)])
#define MBOX_WRITE(device, ibox, value) iowrite32((value), &MBOX(device, ibox))
#define MBOX_READ(device, ibox) ioread32(&MBOX(device, ibox))
#define PD(file) ((struct Acq200Path*)file->private_data)
#define DEV(file) (PD(file)->device)
#define SET_PATH(file, path) (file->private_data = (path))
#define LBUF(file) (PD(file)->scratch)
#define STATUS dbg(1, "STATUS line %d", __LINE__)
#define NULL_A3 NULL
send a command with A3, A4 parameters
#define NULL_A4 NULL
#define TIMESTAMP(a, b, c)
#define ACQ200_PCIWINSZ 0x01000000
#define ACQ200_PCIWINMSK (ACQ200_PCIWINSZ-1)
#define ACQ32_BB_POOL_SIZE 0x100000
#define ACQ32_BB_POOL_ERROR 0xffffffff
#define KMALLOC(size, flags) kmalloc(size, flags)
#define KFREE(addr) kfree(addr)
#define PCI_WINDOW_MASK(device) (dma_buf_len(device) -1)
#define DEVICE_CREATE_FILE(dev, attr) acq200_device_create_file(dev, attr, __FILE__, __LINE__)
#define COPY_TO_USER(src, dest, len) if (copy_to_user(src, dest, len)) { return -EFAULT; }
#define COPY_FROM_USER(src, dest, len) if (copy_from_user(src, dest, len)) { return -EFAULT; }
#define BKL_LOCK 1
#define BKL_UNLOCK 0
#define BKL_QUERY -1
Functions
static int dma_buf_len (struct DmaBuf *dma_buf)
struct Acq200Device * acq200_lookupDevice (struct device *dev)
struct Acq200Device * acq200_lookupDeviceFromClass (struct CLASS_DEVICE *dev)
void acq200_create_sysfs_device (struct device *dev)
void acq200_remove_sysfs_device (struct device *dev)
void acq200_create_sysfs_class (struct Acq200Device *adev)
void acq200_remove_sysfs_class (struct Acq200Device *adev)
int acq200_mmap_host (struct file *file, struct vm_area_struct *vma)
mmap the host buffer.
int acq200_mmap_llhost (struct file *file, struct vm_area_struct *vma)
mmap the host buffer.
int acq200_mmapAB (struct file *file, struct vm_area_struct *vma)
mmap the host buffer.
int acq200_bufferABaction (struct file *file, struct BufferAB_Ops *ops)
int acq200_mmap_mbox (struct file *file, struct vm_area_struct *vma)
provide user mapping to mailboxes on target.
int acq200_map_pci_memory (struct Acq200Device *device)
provide user mapping to mailboxes on target
void acq200_unmap_pci_memory (struct Acq200Device *device)
map remote regs area on device load
int acq200_intsMask (struct Acq200Device *device)
unmap remote regs are on device unload
int acq200_intsDisable (unsigned irqs)
disable interrupts defined by clear bits in irqs
int acq200_intsEnable (unsigned irqs)
enable interrupts defined by set bits in irqs
int acq200_getHeartbeat (struct Acq200Device *device)
int acq200_sendCommand (struct Acq200Device *device, u32 command)
send a command, single parameter
int acq200_sendCommandA3A4 (struct Acq200Device *device, u32 command, u32 a3, u32 a4)
send a command, single parameter
int acq200_sendQuery (struct Acq200Device *device, unsigned command, unsigned *a1, unsigned *a2, unsigned *a3, unsigned *a4)
send a query, pick up answers for aX != NULL
int acq200_getAvailableChannels (struct Acq200Device *device)
send a query, pick up answers for aX != NULL
void acq200_consume_i2o (struct Acq200Device *device, u32 mfa)
void acq200_streaming_isr_bh (unsigned long clidata)
ssize_t acq200_bridge_write (struct file *file, const char *buf, size_t count, loff_t *posp)
ssize_t acq200_bridge_read (struct file *file, char *buf, size_t count, loff_t *posp)
ssize_t acq200_bridge_readAB (struct file *file, char *buf, size_t count, loff_t *posp)
int acq200_bridge_release (struct inode *inode, struct file *file)
int acq200_release (struct inode *inode, struct file *file)
void acq200_pool_create (struct Acq200Device *device)
void acq200_pool_delete (struct Acq200Device *device)
struct IoMapping * acq200_pool_alloc_mapping (struct Acq200Device *device, int direction)
void acq200_pool_free_mapping (struct Acq200Device *device, struct IoMapping *map)
struct ReturnCommandHandler * acq200_pool_alloc_rch (struct Acq200Device *device)
void acq200_pool_free_rch (struct Acq200Device *device, struct ReturnCommandHandler *rch)
int acq200_get_cpci_slot (struct pci_dev *pci_dev)
void acq200_device_create_file (struct device *dev, struct device_attribute *attr, const char *file, int line)
static void copyDmaBuf2IoMapping (struct IoMapping *mapping, struct DmaBuf *dma_buf)
int i2o_missed_int_checker (void *arg)
int acq200_handle_incoming_message (struct Acq200Device *device)
int acq200_bkl (struct Acq200Device *device, int bkl_action)
Variables
int acq200_stub_copy_to_user
Detailed Description
internal header file for acq200 Linux PCI host driver.
Definition in file acq200.h.
Define Documentation
#define ACQ200_IQP 0x40
Definition at line 235 of file acq200.h.
Referenced by acq200_sendI2O_kbuf().
#define ACQ200_MAILBOX_0 0x10
Definition at line 231 of file acq200.h.
#define ACQ200_ODR 0x2c
Definition at line 232 of file acq200.h.
Referenced by acq200_isr().
#define ACQ200_OIMR 0x34
Definition at line 234 of file acq200.h.
Referenced by acq200_incoming_message_isr().
#define ACQ200_OISR 0x30
Definition at line 233 of file acq200.h.
Referenced by acq200_isr().
#define ACQ200_OISR_ODI 0x04
Definition at line 240 of file acq200.h.
Referenced by acq200_isr().
#define ACQ200_OISR_OM_0 0x01
Definition at line 238 of file acq200.h.
#define ACQ200_OISR_OM_1 0x02
Definition at line 239 of file acq200.h.
#define ACQ200_OISR_OPQI 0x08
Definition at line 241 of file acq200.h.
Referenced by acq200_incoming_message_isr(), and acq200_isr().
#define ACQ200_OISR_PCI_INTA 0x10
Definition at line 242 of file acq200.h.
#define ACQ200_ON_CLOSE (file)
Value:
do { \
                if (PD(file) != 0){ \
                         acq200_freePathDescriptor(PD(file));\
                         DG(file)->bridge_dev.open_count--;\
                         PD(file) = 0;\
                } \
                return 0; \
         } while(0)
Definition at line 282 of file acq200.h.
#define ACQ200_ON_OPEN (inode, file)
Value:
do { \
                if ((PD(file)=acq200_makePathDescriptor(inode->i_rdev)) == 0)\
                        return -ENODEV;\
                else \
                         DG(file)->bridge_dev.open_count++; \
         } while(0)
Definition at line 274 of file acq200.h.
#define ACQ200_OQP 0x44
Definition at line 236 of file acq200.h.
Referenced by acq200_dev_i2o_return_mfa(), acq200_handle_incoming_message(), and acq200_incoming_message_isr().
#define ACQ200_PCIWINMSK (ACQ200_PCIWINSZ-1)
Definition at line 402 of file acq200.h.
Referenced by acq200_dev_i2o_mfa2va().
#define ACQ200_PCIWINSZ 0x01000000
Definition at line 401 of file acq200.h.
#define ACQ32_BB_POOL_ERROR 0xffffffff
Definition at line 415 of file acq200.h.
#define ACQ32_BB_POOL_SIZE 0x100000
Definition at line 414 of file acq200.h.
#define BAD_MFA_THRESHOLD 100
Definition at line 225 of file acq200.h.
Referenced by acq200_incoming_message_isr().
#define BKL_LOCK 1
Definition at line 475 of file acq200.h.
Referenced by acq200_bkl(), and store_imask().
#define BKL_QUERY -1
Definition at line 477 of file acq200.h.
Referenced by acq200_bkl(), and store_imask().
#define BKL_UNLOCK 0
Definition at line 476 of file acq200.h.
Referenced by acq200_bkl(), and store_imask().
#define CLASS_DEVICE device
Definition at line 41 of file acq200.h.
#define CLASS_DEVICE_ATTR DEVICE_ATTR
Definition at line 43 of file acq200.h.
#define CLASS_DEVICE_CREATE device_create
Definition at line 42 of file acq200.h.
Referenced by acq200_device_init().
#define CLASS_DEVICE_CREATE_FILE DEVICE_CREATE_FILE
Definition at line 44 of file acq200.h.
#define COPY_FROM_USER (src, dest, len) if (copy_from_user(src, dest, len)) { return -EFAULT; }
Definition at line 457 of file acq200.h.
Referenced by acq200_ioctlAB().
#define COPY_TO_USER (src, dest, len) if (copy_to_user(src, dest, len)) { return -EFAULT; }
Definition at line 454 of file acq200.h.
Referenced by acq200_ioctlAB().
#define CSR (dev, byte_off) ((dev)->csr.va+(byte_off)/4)
Definition at line 246 of file acq200.h.
Referenced by acq200_dev_i2o_return_mfa(), acq200_handle_incoming_message(), acq200_incoming_message_isr(), acq200_isr(), and acq200_sendI2O_kbuf().
#define DEV (file) (PD(file)->device)
Definition at line 304 of file acq200.h.
Referenced by acq200_bridge_openAB(), acq200_bridge_read_generic(), acq200_bridge_readAB(), acq200_bridge_write_generic(), acq200_bufferAB_queue(), acq200_ioctl(), acq200_mbox_ioctl(), acq200_mmap_mbox(), acq200_mmapAB(), acq200_read(), and acq200_release().
#define DEV_TYPE_ACQ16 0x0200
Definition at line 80 of file acq200.h.
#define DEV_TYPE_ACQ164 0x1100
Definition at line 82 of file acq200.h.
#define DEV_TYPE_ACQ196 0x1000
Definition at line 81 of file acq200.h.
Referenced by acq200_set_dev_type().
#define DEV_TYPE_ACQ216 0x2100
Definition at line 84 of file acq200.h.
Referenced by acq200_set_dev_type().
#define DEV_TYPE_ACQ32 0x0100
Definition at line 79 of file acq200.h.
#define DEV_TYPE_WAV232 0x2000
Definition at line 83 of file acq200.h.
#define DEVICE_CREATE_FILE (dev, attr) acq200_device_create_file(dev, attr, __FILE__, __LINE__)
Definition at line 450 of file acq200.h.
Referenced by acq200_create_sysfs_class(), acq200_create_sysfs_device(), and create_dev_sysfs().
#define IS_ACQ196 (ent) ((ent)->vendor == PCI_VENDOR_ID_INTEL)
Definition at line 77 of file acq200.h.
Referenced by acq200_set_dev_type().
#define KFREE (addr) kfree(addr)
Definition at line 440 of file acq200.h.
Referenced by _delete_handlers(), _delete_mappings(), and acq200_pool_delete().
#define KMALLOC (size, flags) kmalloc(size, flags)
Definition at line 439 of file acq200.h.
Referenced by _create_handlers(), _create_mappings(), and acq200_pool_create().
#define KNAME 32
Definition at line 130 of file acq200.h.
#define LBUF (file) (PD(file)->scratch)
Definition at line 307 of file acq200.h.
Referenced by build_hrd_message().
#define LDH_INBOUND -1
Definition at line 270 of file acq200.h.
Referenced by acq200_bridge_release_generic(), acq200_bufferAB_queue(), and build_incoming_raw_message().
#define LDH_NONE 0
Definition at line 271 of file acq200.h.
#define LDH_OUTBOUND 1
last_direction_hack args
Definition at line 269 of file acq200.h.
Referenced by acq200_bridge_release_generic(), and build_outgoing_raw_message().
#define MBOX (device, ibox) (device->csr.va[MBOX_OFFSETL+(ibox)])
Definition at line 296 of file acq200.h.
Referenced by acq200_poll_response().
#define MBOX_OFFSET 0x10
Definition at line 292 of file acq200.h.
#define MBOX_OFFSETL (MBOX_OFFSET/sizeof(u32))
Definition at line 293 of file acq200.h.
#define MBOX_READ (device, ibox) ioread32(&MBOX(device, ibox))
Definition at line 300 of file acq200.h.
Referenced by _getHeartbeat(), acq200_getHeartbeat(), and acq200_ioctl_read_mbox().
#define MBOX_WRITE (device, ibox, value) iowrite32((value), &MBOX(device, ibox))
Definition at line 298 of file acq200.h.
Referenced by _acq200_ioctl_write_mbox().
#define MK_DMABUF_OFFSET (kbuf, device) (kbuf->pa & PCI_WINDOW_MASK(&device->dma_buf))
Definition at line 118 of file acq200.h.
Referenced by acq200_bridge_read_generic(), and acq200_bridge_write_generic().
#define NMAPPINGS 4
Definition at line 74 of file acq200.h.
Referenced by _create_mappings(), and acq200_device_init().
#define NULL_A3 NULL
send a command with A3, A4 parameters
Definition at line 379 of file acq200.h.
Referenced by acq200_getAvailableChannels(), and acq200_sendQuery().
#define NULL_A4 NULL
Definition at line 380 of file acq200.h.
Referenced by acq200_getAvailableChannels(), and acq200_sendQuery().
#define ORDER2LEN (order) ((1<<(order)) * PAGE_SIZE)
Definition at line 128 of file acq200.h.
Referenced by acq200_read(), and get_max_buf().
#define PATH_HEAD (offsetof(struct Acq200Path, scratch))
Definition at line 266 of file acq200.h.
Referenced by acq200_createPath().
#define PCI_I2O_INVALID_MFA 0xffffffff
Definition at line 244 of file acq200.h.
Referenced by acq200_sendI2O_kbuf().
#define PCI_WINDOW_MASK (device) (dma_buf_len(device) -1)
Definition at line 444 of file acq200.h.
#define PD (file) ((struct Acq200Path*)file->private_data)
Definition at line 303 of file acq200.h.
Referenced by acq200_bridge_openAB(), acq200_bridge_read_generic(), acq200_bridge_release_generic(), acq200_bridge_release_message(), acq200_bridge_releaseAB(), acq200_bridge_write_generic(), acq200_bufferAB_queue(), acq200_bufferABaction(), acq200_bufferABrecycle(), acq200_ioctlAB(), acq200_mbox_ioctl(), acq200_mmap_host(), acq200_mmap_llhost(), acq200_mmapAB(), acq200_release(), and build_hrd_message().
#define RCH_KB_POOL 1
Definition at line 92 of file acq200.h.
Referenced by acq200_bridge_read_generic(), acq200_bridge_release_message(), acq200_bridge_write_generic(), acq200_bufferAB_queue(), and i2o_recycleRch().
#define RESPONSE_RECEIVED (dev) ((dev)->mbox_sync.response_received != 0)
Definition at line 247 of file acq200.h.
Referenced by acq200_ioctl_wbr_mbox().
#define SET_PATH (file, path) (file->private_data = (path))
Definition at line 305 of file acq200.h.
Referenced by acq200_open().
#define STATUS dbg(1, "STATUS line %d", __LINE__)
Definition at line 364 of file acq200.h.
Referenced by acq200_mmap_mbox(), and mmap_dmabuf().
#define TIMESTAMP (a, b, c)
Definition at line 400 of file acq200.h.
Referenced by acq200_consume_i2o(), and acq200_streaming_isr_bh().
#define USE_POOL 0
Definition at line 121 of file acq200.h.
Referenced by acq200_bridge_read().
Function Documentation
int acq200_bkl (struct Acq200Device * device, int bkl_action)
Definition at line 153 of file acq200_utils.c.
References Acq200Device::bkl, BKL_LOCK, BKL_QUERY, BKL_UNLOCK, Acq200Device::BKL::flags, info, Acq200Device::BKL::is_locked, and Acq200Device::BKL::lock.
Referenced by store_imask().
ssize_t acq200_bridge_read (struct file * file, char * buf, size_t count, loff_t * posp)
Definition at line 604 of file acq200_i2o.c.
References acq200_bridge_read_generic(), HRD_CHAN_IS_FILE, and USE_POOL.
Referenced by acq200_open().
ssize_t acq200_bridge_readAB (struct file * file, char * buf, size_t count, loff_t * posp)
Definition at line 611 of file acq200_i2o.c.
References Acq200Device::AB, acq200_bridge_read_generic(), dbg, DEV, dma_buf_len(), HRD_ABS_PCI, HRD_CHAN_IS_FILE, DmaBuf::pa, user_max_buf, and DmaBuf::va.
Referenced by acq200_open().
int acq200_bridge_release (struct inode * inode, struct file * file)
Definition at line 865 of file acq200_i2o.c.
References acq200_bridge_release_generic(), and HRD_CHAN_IS_FILE.
Referenced by acq200_bridge_releaseAB(), and acq200_open().
ssize_t acq200_bridge_write (struct file * file, const char * buf, size_t count, loff_t * posp)
Definition at line 594 of file acq200_i2o.c.
References acq200_bridge_write_generic(), dbg, and HRD_CHAN_IS_FILE.
Referenced by acq200_open().
int acq200_bufferABaction (struct file * file, struct BufferAB_Ops * ops)
Definition at line 739 of file acq200_i2o.c.
References Acq200Path::ab_next, acq200_bufferAB_queue(), acq200_bufferABrecycle(), BUFFERA, BUFFERB, BufferAB_Ops::ci, dbg, BufferAB_Ops::ds, err, fillDeviceStatus(), BufferAB_Ops::DriverStatus::full, PD, Acq200Path::rchAB, ReturnCommandHandler::rchReturn, Acq200Path::return_waitq, BufferAB_Ops::ClientInstructions::timeout, and RchReturn::valid.
Referenced by acq200_ioctlAB().
void acq200_consume_i2o (struct Acq200Device * device, u32 mfa)
Definition at line 413 of file acq200_i2o.c.
References acq200_debug, dbg, Acq200Device::DevicePrivateData::i2o_last_in, Acq200Device::DevicePrivateData::i2o_packets_discarded, Acq200Device::DevicePrivateData::i2o_packets_incoming, i2o_return_message(), Acq200Device::m_dpd, Acq200Device::streambuf, Acq200Device::DevicePrivateData::streaming_isr_tasklet, streamPut(), and TIMESTAMP.
Referenced by acq200_handle_incoming_message(), and acq200_incoming_message_isr().
void acq200_create_sysfs_class (struct Acq200Device * adev)
Definition at line 417 of file acq200_if.c.
References Acq200Device::class_dev, dbg, DEVICE_CREATE_FILE, err, and Acq200Device::pci_dev.
Referenced by acq200_device_init().
void acq200_create_sysfs_device (struct device * dev)
Definition at line 280 of file acq200_if.c.
References dbg, and DEVICE_CREATE_FILE.
Referenced by acq200_device_init().
void acq200_device_create_file (struct device * dev, struct device_attribute * attr, const char * file, int line)
Definition at line 270 of file acq200_if.c.
References err.
int acq200_get_cpci_slot (struct pci_dev * pci_dev)
Definition at line 74 of file acq200_if.c.
Referenced by acq200_device_init(), and show_cpci_slot().
int acq200_getAvailableChannels (struct Acq200Device * device)
send a query, pick up answers for aX != NULL
update available input, output channels from device
Definition at line 102 of file acq200_core.c.
References acq200_sendQuery(), BP_SET_FUNCODE, BPFC_GET_NCHANNELS, err, Acq200Device::input_channels, Acq200Device::CHANNEL_INFO::nchannels, NULL_A3, NULL_A4, and Acq200Device::output_channels.
Referenced by acq200_device_init().
int acq200_getHeartbeat (struct Acq200Device * device)
Definition at line 56 of file acq200_core.c.
References _getHeartbeat(), dbg, Acq200Device::heartbeat_detected, and MBOX_READ.
Referenced by show_heartbeat().
int acq200_handle_incoming_message (struct Acq200Device * device)
Definition at line 833 of file acq200.c.
References acq200_consume_i2o(), ACQ200_OQP, Acq200Device::DevicePrivateData::bad_mfa_count, CSR, dbg, and Acq200Device::m_dpd.
Referenced by i2o_missed_int_checker().
int acq200_intsDisable (unsigned irqs)
disable interrupts defined by clear bits in irqs
Parameters:
irqs disable interrupts defined by clear bits in irqs
Definition at line 84 of file acq200_utils.c.
References getNext(), and hasNext().
Referenced by acq200_ioctl().
int acq200_intsEnable (unsigned irqs)
enable interrupts defined by set bits in irqs
Parameters:
irqs enable interrupts defined by set bits in irqs
Definition at line 94 of file acq200_utils.c.
References getNext(), and hasNext().
Referenced by acq200_ioctl().
int acq200_intsMask (struct Acq200Device * device)
unmap remote regs are on device unload
disable interrupts defined by set bits in imask, a string of hex chars
Parameters:
device disable interrupts defined by clear bits in irqs re-enable interrupts that are not masked this time, but were last time.
Definition at line 113 of file acq200_utils.c.
References acq200_debug, dbg, get_mask(), Acq200Device::imask, and Acq200Device::imask_a.
Referenced by store_imask().
struct Acq200Device* acq200_lookupDevice (struct device * dev) [read]
Definition at line 322 of file acq200.c.
References idx, and Acq200Device::pci_dev.
Referenced by acq200_remove(), show_available_input_channels(), show_available_output_channels(), show_buffer_AB_busy_mutex(), show_buffers(), show_cpci_slot(), show_heartbeat(), show_host_len(), show_host_pa(), show_interrupt_count(), show_llhost_len(), show_llhost_pa(), show_pool(), and show_rch_list().
struct Acq200Device* acq200_lookupDeviceFromClass (struct CLASS_DEVICE * dev) [read]
Definition at line 336 of file acq200.c.
References Acq200Device::class_dev, and idx.
Referenced by show_dev(), show_imask(), and store_imask().
int acq200_map_pci_memory (struct Acq200Device * device)
provide user mapping to mailboxes on target
Definition at line 78 of file acq200_mmap.c.
References acq200_makeIoMapping(), CSR_SIZE, and PCI_BA_CSR.
Referenced by acq200_device_create().
int acq200_mmap_host (struct file * file, struct vm_area_struct * vma)
mmap the host buffer.
Definition at line 159 of file acq200_mmap.c.
References mmap_dmabuf(), and PD.
Referenced by acq200_open().
int acq200_mmap_llhost (struct file * file, struct vm_area_struct * vma)
mmap the host buffer.
Definition at line 167 of file acq200_mmap.c.
References mmap_dmabuf(), and PD.
Referenced by acq200_open().
int acq200_mmap_mbox (struct file * file, struct vm_area_struct * vma)
provide user mapping to mailboxes on target.
follows LDD3.pg429
Definition at line 187 of file acq200_mmap.c.
References Acq200Device::csr, CSR_SIZE_MAX, DEV, Acq200Device::IoMapping::pa, and STATUS.
Referenced by acq200_open().
int acq200_mmapAB (struct file * file, struct vm_area_struct * vma)
mmap the host buffer.
mmap the host buffer.
follows LDD3.pg429
Definition at line 175 of file acq200_mmap.c.
References Acq200Device::AB, DEV, mmap_dmabuf(), and PD.
Referenced by acq200_open().
struct IoMapping* acq200_pool_alloc_mapping (struct Acq200Device * device, int direction) [read]
Definition at line 225 of file acq200_bigbuf_alloc.c.
References _alloc(), dbg, BigBufPool::mappings, and Acq200Device::pool.
Referenced by acq200_bridge_read_generic(), and acq200_bridge_write_generic().
struct ReturnCommandHandler* acq200_pool_alloc_rch (struct Acq200Device * device) [read]
Definition at line 243 of file acq200_bigbuf_alloc.c.
References _alloc(), dbg, BigBufPool::handlers, and Acq200Device::pool.
Referenced by acq200_bridge_read_generic(), acq200_bridge_release_message(), acq200_bridge_write_generic(), and acq200_bufferAB_queue().
void acq200_pool_create (struct Acq200Device * device)
Definition at line 148 of file acq200_bigbuf_alloc.c.
References _create_handlers(), _create_mappings(), create_dev_sysfs(), BigBufPool::Pool::entries, KMALLOC, BigBufPool::mappings, MSG_MAPPING, Acq200Device::pci_dev, Acq200Device::pool, PoolEntry::reserved, and BigBufPool::sleepq.
Referenced by acq200_device_create().
void acq200_pool_delete (struct Acq200Device * device)
Definition at line 164 of file acq200_bigbuf_alloc.c.
References _delete_handlers(), _delete_mappings(), KFREE, Acq200Device::pci_dev, Acq200Device::pool, and remove_dev_sysfs().
Referenced by acq200_device_free().
void acq200_pool_free_mapping (struct Acq200Device * device, struct IoMapping * map)
Definition at line 236 of file acq200_bigbuf_alloc.c.
References _free(), dbg, BigBufPool::mappings, and Acq200Device::pool.
Referenced by acq200_bridge_read_generic(), and i2o_recycleRch().
void acq200_pool_free_rch (struct Acq200Device * device, struct ReturnCommandHandler * rch)
Definition at line 253 of file acq200_bigbuf_alloc.c.
References _free(), dbg, BigBufPool::handlers, and Acq200Device::pool.
Referenced by i2o_recycleRch().
int acq200_release (struct inode * inode, struct file * file)
Definition at line 1146 of file acq200.c.
References acq200_deletePath(), acq200_ioctl_wbr_mbox(), Acq200Device::buffer_AB_busy_mutex, dbg, DEV, Acq200Path::device, Acq200Path::has_AB_busy_mutex, MailboxControl::mbc_flags, MBC_FLAGS_ONRELEASE, Acq200Path::mbc_on_release, and PD.
Referenced by acq200_bridge_release_generic(), acq200_bridge_release_message(), acq200_device_init(), and acq200_open().
void acq200_remove_sysfs_class (struct Acq200Device * adev)
Definition at line 437 of file acq200_if.c.
References Acq200Device::class_dev.
Referenced by acq200_remove().
void acq200_remove_sysfs_device (struct device * dev)
Definition at line 298 of file acq200_if.c.
Referenced by acq200_remove().
int acq200_sendCommand (struct Acq200Device * device, u32 command)
send a command, single parameter
Definition at line 764 of file acq200.c.
References acq200_ioctl_wbr_mbox(), BP_CI_COMMAND, BP_CI_DONE, BP_MB_COMMAND, DEFTO, MailboxControl::mbc_flags, MBC_TO_MBXR, MBC_TO_MBXW, and MailboxControl::mbxw.
Referenced by acq200_device_init().
int acq200_sendCommandA3A4 (struct Acq200Device * device, u32 command, u32 a3, u32 a4)
send a command, single parameter
Definition at line 775 of file acq200.c.
References acq200_ioctl_wbr_mbox(), BP_CI_COMMAND, BP_CI_DONE, BP_MB_A3, BP_MB_A4, BP_MB_COMMAND, DEFTO, MailboxControl::mbc_flags, MBC_TO_MBXR, MBC_TO_MBXW, and MailboxControl::mbxw.
Referenced by acq200_device_init().
int acq200_sendQuery (struct Acq200Device * device, unsigned command, unsigned * a1, unsigned * a2, unsigned * a3, unsigned * a4)
send a query, pick up answers for aX != NULL
Definition at line 793 of file acq200.c.
References acq200_ioctl_wbr_mbox(), BP_CI_DONE, BP_CI_QUERY, BP_GET_A1, BP_GET_A2, BP_MB_A3, BP_MB_A4, BP_MB_COMMAND, DEFTO, MailboxControl::mbc_flags, MBC_TO_MBXR, MBC_TO_MBXW, MailboxControl::mbxr, MailboxControl::mbxw, NULL_A3, and NULL_A4.
Referenced by acq200_getAvailableChannels().
void acq200_streaming_isr_bh (unsigned long clidata)
Definition at line 348 of file acq200_i2o.c.
References acq200_debug, acq200_dev_i2o_mfa2va(), acq200_processCommandMessageReturn(), Acq200Device::DevicePrivateData::aux_mfa, Acq200Device::DevicePrivateData::aux_task_waiting, Acq200Device::DevicePrivateData::aux_waitq, dbg, MESSAGE::header, Acq200Device::DevicePrivateData::i2o_packets_discarded, i2o_return_message(), MESSAGE_HEADER::id, MESSAGE_HEADER::length, Acq200Device::m_dpd, MT_COMMAND_PACKET, MT_ID, MT_STREAM, STREAM_MFA_INVALID, Acq200Device::streambuf, streamGet(), Acq200Device::DevicePrivateData::streaming_enabled, streamPut(), TIMESTAMP, and MESSAGE_HEADER::type.
Referenced by acq200_device_create().
void acq200_unmap_pci_memory (struct Acq200Device * device)
map remote regs area on device load
Definition at line 102 of file acq200_mmap.c.
References clearIoMapping(), and Acq200Device::csr.
Referenced by acq200_device_free().
static void copyDmaBuf2IoMapping (struct IoMapping * mapping, struct DmaBuf * dma_buf) [inline, static]
Definition at line 463 of file acq200.h.
References dma_buf_len(), DmaBuf::pa, and DmaBuf::va.
Referenced by acq200_bridge_openAB().
static int dma_buf_len (struct DmaBuf * dma_buf) [inline, static]
Definition at line 309 of file acq200.h.
References DmaBuf::order, and DmaBuf::va.
Referenced by _create_mappings(), acq200_bridge_readAB(), acq200_bufferAB_queue(), acq200_device_create(), acq200_device_init(), alloc_max_buf(), copyDmaBuf2IoMapping(), dumpDmaBuf(), mmap_dmabuf(), show_host_len(), and show_llhost_len().
int i2o_missed_int_checker (void * arg)
Definition at line 709 of file acq200_i2o.c.
References acq200_handle_incoming_message(), dbg, I2O_RETRY, Acq200Device::idx, info, and timeout.
Referenced by acq200_onFirstClientOpenAB().
Variable Documentation
int acq200_stub_copy_to_user
Definition at line 293 of file acq200.c.
Referenced by acq200_copy_from_io_to_user().