ACQ200 HOSTDRV: acq200_utils.c File Reference
acq200_utils.c File Reference
#include <linux/module.h>
#include <linux/interrupt.h>
#include <linux/kernel.h>
#include <linux/fs.h>
#include <linux/errno.h>
#include <linux/types.h>
#include <linux/proc_fs.h>
#include <linux/fcntl.h>
#include <linux/pci.h>
#include <linux/sched.h>
#include <asm/io.h>
#include <asm/irq.h>
#include <asm/uaccess.h>
#include <asm/system.h>
#include <asm/segment.h>
#include "acq200_debug.h"
#include "acq200.h"
Data Structures
struct MASK_ITERATOR
Defines
#define CONFIG_GENERIC_HARDIRQS 1
Functions
int hasNext (struct MASK_ITERATOR *it)
int getNext (struct MASK_ITERATOR *it)
int acq200_intsDisable (unsigned irqs)
disable interrupts defined by clear bits in irqs
int acq200_intsEnable (unsigned irqs)
enable interrupts defined by set bits in irqs
static unsigned get_mask (char mdef)
int acq200_intsMask (struct Acq200Device *device)
unmap remote regs are on device unload
int acq200_bkl (struct Acq200Device *device, int bkl_action)
Define Documentation
#define CONFIG_GENERIC_HARDIRQS 1
Definition at line 3 of file acq200_utils.c.
Function Documentation
int acq200_bkl (struct Acq200Device * device, int bkl_action)
Definition at line 153 of file acq200_utils.c.
References Acq200Device::bkl, BKL_LOCK, BKL_QUERY, BKL_UNLOCK, Acq200Device::BKL::flags, info, Acq200Device::BKL::is_locked, and Acq200Device::BKL::lock.
Referenced by store_imask().
int acq200_intsDisable (unsigned irqs)
disable interrupts defined by clear bits in irqs
Parameters:
irqs disable interrupts defined by clear bits in irqs
Definition at line 84 of file acq200_utils.c.
References getNext(), and hasNext().
Referenced by acq200_ioctl().
int acq200_intsEnable (unsigned irqs)
enable interrupts defined by set bits in irqs
Parameters:
irqs enable interrupts defined by set bits in irqs
Definition at line 94 of file acq200_utils.c.
References getNext(), and hasNext().
Referenced by acq200_ioctl().
int acq200_intsMask (struct Acq200Device * device)
unmap remote regs are on device unload
disable interrupts defined by set bits in imask, a string of hex chars
Parameters:
device disable interrupts defined by clear bits in irqs re-enable interrupts that are not masked this time, but were last time.
Definition at line 113 of file acq200_utils.c.
References acq200_debug, dbg, get_mask(), Acq200Device::imask, and Acq200Device::imask_a.
Referenced by store_imask().
static unsigned get_mask (char mdef) [static]
Definition at line 105 of file acq200_utils.c.
Referenced by acq200_intsMask().
int getNext (struct MASK_ITERATOR * it)
Definition at line 57 of file acq200_utils.c.
References MASK_ITERATOR::icursor, and MASK_ITERATOR::mask.
Referenced by acq200_intsDisable(), and acq200_intsEnable().
int hasNext (struct MASK_ITERATOR * it)
Definition at line 35 of file acq200_utils.c.
References MASK_ITERATOR::icursor, and MASK_ITERATOR::mask.
Referenced by acq200_intsDisable(), and acq200_intsEnable().