ACQ200 HOSTDRV: acqcmd.c File Reference
acqcmd.c File Reference
CLI application to acq2xx.
#include "local.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "popt.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
#include <sys/time.h>
Defines
#define acq200_debug verbose
#define HELP
#define FNAME "/dev/acq32/acq32.1.m1"
#define ENV "ACQCMD_DEV"
#define MFMT "/dev/acq32/acq32.%d.m%d"
#define SHELL_FMT "/dev/acq200/acq200.%d.rsh"
#define MAXLINE 4096
#define PRINTF if (verbose) printf
#define ERROR_STRING "ACQ32:ERROR"
#define ERROR_LEN strlen(ERROR_STRING)
#define ISCOMMENT(cl) (cl[0]=='#')
#define ISBLANK(cl) (strlen(cl)<=1)
Functions
static int process_command (FILE *fd)
static int process_stdin (FILE *fd)
static int do_poll (const char *device, FILE *fd, const char *command, const char *do_while, const char *do_until)
static int is_socket (const char *file)
static void alarm_handler (int signum)
static void install_handlers (void)
static FILE * make_connection (const char *device)
int main (int argc, const char *argv[])
static int iscontinuation (char *line)
Variables
poptContext opt_context
int verbose = 0
static int sock
static int timed_out
Detailed Description
CLI application to acq2xx.
Revision:
1.13
acqcmd is the general command line interface to acq2xx control. It offers the same interface on
CPCI backplane device
Remote HUB device
run locally on the card itself
USAGE: acqcmd [opts] [command]
if command is omitted, take commands from stdin.
-b Board : send "acqcmd" to Board
-s Board : run shell command on Board (not used in local command case)
Examples:
Local: acqcmd getNumSamples
Backplane: acqcmd -b 2 getNumSamples (query card in physical slot 2)
Hub: acqcmd -b 20 getNumSamples (query card in logical slot 20)
Backplane: acqcmd -s 2 'echo `hostname` `get.release.versions`' (run shell command on remote)
Specialized Usage
--until ST_xxxx (run until state ST_xxxx eg acqcmd --until ST_STOP)
--while ST_xxxx (run while state ST_xxxx eg acqcmd --while ST_RUN)
--timeout T (timeout on command completion - useful with --until, while).
Definition in file acqcmd.c.
Define Documentation
#define acq200_debug verbose
Definition at line 87 of file acqcmd.c.
#define ENV "ACQCMD_DEV"
Definition at line 140 of file acqcmd.c.
Referenced by main().
#define ERROR_LEN strlen(ERROR_STRING)
Definition at line 322 of file acqcmd.c.
Referenced by process_command().
#define ERROR_STRING "ACQ32:ERROR"
Definition at line 321 of file acqcmd.c.
Referenced by process_command().
#define FNAME "/dev/acq32/acq32.1.m1"
Definition at line 137 of file acqcmd.c.
Referenced by main().
#define HELP
Value:
"acqcmd $Revision: 1.13 $ B1005\n"\
"acqcmd [-f device][-b board {1..7}] command\n"\
"or export ACQCMD_DEV=device\n"\
""
Definition at line 128 of file acqcmd.c.
Referenced by main().
#define ISBLANK (cl) (strlen(cl)<=1)
Definition at line 459 of file acqcmd.c.
Referenced by process_stdin().
#define ISCOMMENT (cl) (cl[0]=='#')
Definition at line 458 of file acqcmd.c.
Referenced by process_stdin().
#define MAXLINE 4096
Definition at line 150 of file acqcmd.c.
Referenced by process_stdin().
#define MFMT "/dev/acq32/acq32.%d.m%d"
Definition at line 142 of file acqcmd.c.
Referenced by main().
#define PRINTF if (verbose) printf
Definition at line 152 of file acqcmd.c.
Referenced by do_poll(), main(), and process_stdin().
#define SHELL_FMT "/dev/acq200/acq200.%d.rsh"
Definition at line 143 of file acqcmd.c.
Referenced by main().
Function Documentation
static void alarm_handler (int signum) [static]
Definition at line 178 of file acqcmd.c.
References timed_out.
Referenced by install_handlers().
static int do_poll (const char * device, FILE * fd, const char * command, const char * do_while, const char * do_until) [static]
pci driver caches value
Definition at line 356 of file acqcmd.c.
References make_connection(), PRINTF, sock, and verbose.
Referenced by main().
static void install_handlers (void) [static]
Definition at line 186 of file acqcmd.c.
References alarm_handler().
Referenced by main().
static int is_socket (const char * file) [static]
Definition at line 163 of file acqcmd.c.
Referenced by make_connection().
static int iscontinuation (char * line) [static]
Definition at line 461 of file acqcmd.c.
Referenced by process_stdin().
int main (int argc, const char * argv[])
Definition at line 244 of file acqcmd.c.
References do_poll(), ENV, FNAME, HELP, install_handlers(), make_connection(), MFMT, opt_context, PRINTF, process_command(), process_stdin(), SHELL_FMT, STREQ, timeout, and verbose.
static FILE* make_connection (const char * device) [static]
Definition at line 200 of file acqcmd.c.
References is_socket(), and sock.
Referenced by do_poll(), and main().
static int process_command (FILE * fd) [static]
Definition at line 324 of file acqcmd.c.
References err, ERROR_LEN, ERROR_STRING, opt_context, and STREQ.
Referenced by main().
static int process_stdin (FILE * fd) [static]
Definition at line 478 of file acqcmd.c.
References ISBLANK, ISCOMMENT, iscontinuation(), MAXLINE, PRINTF, and STREQ.
Referenced by main().
Variable Documentation
poptContext opt_context
Definition at line 146 of file acqcmd.c.
Referenced by main(), and process_command().
int sock [static]
Definition at line 171 of file acqcmd.c.
Referenced by do_poll(), and make_connection().
int timed_out [static]
Definition at line 176 of file acqcmd.c.
Referenced by alarm_handler().
int verbose = 0
Definition at line 147 of file acqcmd.c.
Referenced by do_poll(), and main().