ACQ200 HOSTDRV: int-disable-test.c File Reference
int-disable-test.c File Reference
#include "local.h"
#include <assert.h>
Defines
#define IRQ_STATUS "/proc/interrupts"
#define IRQ_MASK "/dev/acq200/acq200.%d.imask"
Functions
void set_mask (char *mask)
void test_loop (volatile int loopcount)
void dump_state (char *mask, char *id)
void run_test (char *MASK)
void init_defaults (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
int SLOT = 2
int LOOPCOUNT = 1
char * MASK = "0"
char * NOMASK = "00000000"
Detailed Description
runs a "calculation loop".
first with interrupts on, then masked according to a command line mask
Usage: int-disable-test MASK [loopcount]
Definition in file int-disable-test.c.
Define Documentation
#define IRQ_MASK "/dev/acq200/acq200.%d.imask"
Definition at line 36 of file int-disable-test.c.
Referenced by set_mask().
#define IRQ_STATUS "/proc/interrupts"
Definition at line 35 of file int-disable-test.c.
Referenced by dump_state().
Function Documentation
void dump_state (char * mask, char * id)
Definition at line 72 of file int-disable-test.c.
References IRQ_STATUS.
Referenced by run_test().
void init_defaults (int argc, char * argv[])
Definition at line 86 of file int-disable-test.c.
References assert, IN_RANGE, LOOPCOUNT, MASK, and SLOT.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 106 of file int-disable-test.c.
References init_defaults(), MASK, NOMASK, run_test(), and set_mask().
void run_test (char * MASK)
Definition at line 78 of file int-disable-test.c.
References dump_state(), LOOPCOUNT, and test_loop().
Referenced by main().
void set_mask (char * mask)
Definition at line 46 of file int-disable-test.c.
References assert, IRQ_MASK, and SLOT.
Referenced by main().
void test_loop (volatile int loopcount)
Definition at line 58 of file int-disable-test.c.
Referenced by run_test().
Variable Documentation
int LOOPCOUNT = 1
Definition at line 39 of file int-disable-test.c.
Referenced by init_defaults(), and run_test().
char* MASK = "0"
Definition at line 40 of file int-disable-test.c.
Referenced by init_defaults(), and main().
char* NOMASK = "00000000"
Definition at line 42 of file int-disable-test.c.
Referenced by main().
int SLOT = 2
Definition at line 38 of file int-disable-test.c.