ACQ200 HOSTDRV: rch.h File Reference
rch.h File Reference
Defines
#define RCH struct ReturnCommandHandler
Functions
static void rchInsert (struct list_head *head, RCH *new_entry)
static void rchAppend (struct list_head *head, RCH *new_entry)
static void rchRemove (RCH *rch)
static int rchRemoveIfNotValid (RCH *rch)
timeout action.
void rchInit (struct Acq200Device *device, RCH *rch)
init return command handler
static struct Acq200Path * rchSetSamplesAndGetPath (RCH *rch, unsigned id, int nsamples)
Define Documentation
#define RCH struct ReturnCommandHandler
Definition at line 7 of file rch.h.
Function Documentation
static void rchAppend (struct list_head * head, RCH * new_entry) [inline, static]
Definition at line 18 of file rch.h.
Referenced by acq200_bridge_read_generic(), acq200_bridge_release_message(), acq200_bridge_write_generic(), and acq200_bufferAB_queue().
void rchInit (struct Acq200Device * device, RCH * rch)
init return command handler
Parameters:
device
rch = null means init device global rch
static void rchInsert (struct list_head * head, RCH * new_entry) [inline, static]
Definition at line 9 of file rch.h.
static void rchRemove (RCH * rch) [inline, static]
Definition at line 27 of file rch.h.
References dbg.
Referenced by i2o_recycleRch().
static int rchRemoveIfNotValid (RCH * rch) [inline, static]
timeout action.
Definition at line 39 of file rch.h.
References dbg.
Referenced by acq200_bridge_read_generic().
static struct Acq200Path* rchSetSamplesAndGetPath (RCH * rch, unsigned id, int nsamples) [static, read]
Definition at line 65 of file rch.h.
Referenced by i2o_handleReadMessageFile().