ACQ200 HOSTDRV: streambuf.h File Reference
streambuf.h File Reference
Data Structures
struct GenericIntBuf
struct StreamBuf
struct StatBuf
struct AppBuf
Defines
#define NSTREAMBUF (1<<7)
#define NSTATBUF (1<<4)
#define STREAM_MFA_INVALID 0xFFFFFFFFU
#define streamDump(a, b)
Functions
static void genericIntBufInit (struct GenericIntBuf *buf, int nbuf)
static int genericIntBufInc (struct GenericIntBuf *buf, int ii)
static int genericIntBufIsFull (struct GenericIntBuf *buf)
static int genericIntBufIsEmpty (struct GenericIntBuf *buf)
static int genericIntBufPut (struct GenericIntBuf *buf, u32 data)
static u32 genericIntBufGet (struct GenericIntBuf *buf)
static void genericIntBufPutBack (struct GenericIntBuf *buf)
static int genericIntBufNumEntries (struct GenericIntBuf *buf)
static void streamBufInit (struct StreamBuf *stream_buf)
static int streamPut (struct StreamBuf *stream_buf, u32 data)
static u32 streamGet (struct StreamBuf *stream_buf)
static void streamPutBack (struct StreamBuf *stream_buf)
static int streamNumEntries (struct StreamBuf *stream_buf)
static int statbufPut (struct StatBuf *stat_buf, u32 data)
static u32 statbufGet (struct StatBuf *stat_buf)
static int statbufIsEmpty (struct StatBuf *stat_buf)
static void statBufInit (struct StatBuf *buf)
static void appbufInit (struct AppBuf *app_buf)
Define Documentation
#define NSTATBUF (1<<4)
Definition at line 28 of file streambuf.h.
Referenced by statBufInit().
#define NSTREAMBUF (1<<7)
Definition at line 19 of file streambuf.h.
Referenced by streamBufInit().
#define STREAM_MFA_INVALID 0xFFFFFFFFU
Definition at line 40 of file streambuf.h.
Referenced by acq200_streaming_isr_bh(), and genericIntBufGet().
#define streamDump (a, b)
Definition at line 47 of file streambuf.h.
Referenced by genericIntBufGet(), and genericIntBufPut().
Function Documentation
static void appbufInit (struct AppBuf * app_buf) [inline, static]
Definition at line 155 of file streambuf.h.
References AppBuf::count_actual, and AppBuf::count_max.
static u32 genericIntBufGet (struct GenericIntBuf * buf) [inline, static]
Definition at line 83 of file streambuf.h.
References GenericIntBuf::buffers, genericIntBufInc(), genericIntBufIsEmpty(), GenericIntBuf::iget, GenericIntBuf::iputback, GenericIntBuf::lock, STREAM_MFA_INVALID, and streamDump.
Referenced by statbufGet(), and streamGet().
static int genericIntBufInc (struct GenericIntBuf * buf, int ii) [inline, static]
Definition at line 55 of file streambuf.h.
References GenericIntBuf::buffer_mask.
Referenced by genericIntBufGet(), genericIntBufIsFull(), genericIntBufNumEntries(), and genericIntBufPut().
static void genericIntBufInit (struct GenericIntBuf * buf, int nbuf) [inline, static]
Definition at line 50 of file streambuf.h.
References GenericIntBuf::buffer_mask, GenericIntBuf::iget, GenericIntBuf::iput, GenericIntBuf::iputback, and GenericIntBuf::lock.
Referenced by statBufInit(), and streamBufInit().
static int genericIntBufIsEmpty (struct GenericIntBuf * buf) [inline, static]
Definition at line 62 of file streambuf.h.
References GenericIntBuf::iget, and GenericIntBuf::iput.
Referenced by genericIntBufGet(), and statbufIsEmpty().
static int genericIntBufIsFull (struct GenericIntBuf * buf) [inline, static]
Definition at line 58 of file streambuf.h.
References genericIntBufInc(), GenericIntBuf::iput, and GenericIntBuf::iputback.
Referenced by genericIntBufPut().
static int genericIntBufNumEntries (struct GenericIntBuf * buf) [inline, static]
Definition at line 108 of file streambuf.h.
References genericIntBufInc(), GenericIntBuf::iget, and GenericIntBuf::iput.
Referenced by streamNumEntries().
static int genericIntBufPut (struct GenericIntBuf * buf, u32 data) [inline, static]
Definition at line 65 of file streambuf.h.
References GenericIntBuf::buffers, genericIntBufInc(), genericIntBufIsFull(), GenericIntBuf::iput, GenericIntBuf::iswrapped, GenericIntBuf::nwrapped, and streamDump.
Referenced by statbufPut(), and streamPut().
static void genericIntBufPutBack (struct GenericIntBuf * buf) [inline, static]
Definition at line 103 of file streambuf.h.
References GenericIntBuf::iget, and GenericIntBuf::iputback.
Referenced by streamPutBack().
static u32 statbufGet (struct StatBuf * stat_buf) [inline, static]
Definition at line 145 of file streambuf.h.
References StatBuf::def, and genericIntBufGet().
static void statBufInit (struct StatBuf * buf) [inline, static]
Definition at line 152 of file streambuf.h.
References StatBuf::def, genericIntBufInit(), and NSTATBUF.
static int statbufIsEmpty (struct StatBuf * stat_buf) [inline, static]
Definition at line 148 of file streambuf.h.
References StatBuf::def, and genericIntBufIsEmpty().
static int statbufPut (struct StatBuf * stat_buf, u32 data) [inline, static]
Definition at line 142 of file streambuf.h.
References StatBuf::def, and genericIntBufPut().
static void streamBufInit (struct StreamBuf * stream_buf) [inline, static]
Definition at line 122 of file streambuf.h.
References StreamBuf::def, genericIntBufInit(), and NSTREAMBUF.
Referenced by acq200_device_create().
static u32 streamGet (struct StreamBuf * stream_buf) [inline, static]
Definition at line 128 of file streambuf.h.
References StreamBuf::def, and genericIntBufGet().
Referenced by acq200_streaming_isr_bh().
static int streamNumEntries (struct StreamBuf * stream_buf) [inline, static]
Definition at line 136 of file streambuf.h.
References StreamBuf::def, and genericIntBufNumEntries().
static int streamPut (struct StreamBuf * stream_buf, u32 data) [inline, static]
Definition at line 125 of file streambuf.h.
References StreamBuf::def, and genericIntBufPut().
Referenced by acq200_consume_i2o(), and acq200_streaming_isr_bh().
static void streamPutBack (struct StreamBuf * stream_buf) [inline, static]
Definition at line 131 of file streambuf.h.
References StreamBuf::def, and genericIntBufPutBack().